### ISSUE TITLE
how to specify authorization header programmatically?

### ISSUE THREAD

**Issue by OneCyrus** [dotansimha/graphql-code-generator#1167]
with the new config file we need to specify the authorization token in the config file according to the documentation:
https://graphql-code-generator.com/docs/getting-started/schema-field#url

with the old version we supplied the token at runtime (as it changes very often). is there no option to specify the key when executing the command?

**Comment by kamilkisiela** [comment]
Hi :)

```ts
{
  schema: {
    'URL-HERE' : {
      headers: {
        Authorization: 'TOKEN-HERE'
      }
    }
  }
}
```

[Related part of the codebase](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/src/yml-config-types.ts#L10)

Thanks to recent changes, GraphQL Code Generator supports `.js` file as a config. So instead of passing `codegen.yml` you can now use `codegen.js` :)
