### ISSUE TITLE
Document differences with Apollo Codegen

### ISSUE THREAD

**Issue by altschuler** [dotansimha/graphql-code-generator#118]
I'm using this project because at the time of adoption [apollo-codegen](https://github.com/apollographql/apollo-codegen) did not support the `gql` tag. Now that it does I'm not so sure what the difference between this project and Apollo's version is.

Could it be documented? (I'd make a PR, but I can't because I don't know...)

And thank you for an awesome library, it's been one of the huge advantages of using graphql :)

**Comment by dotansimha** [comment]
@altschuler 
Basically, `apollo-codegen` generates a similar results, but it based on code that generates the results. 
This package uses Templates (with Handlebars) to generate results, and it basically supports any output because you can simply create you template and then compile it with your GraphQL schema and  get a more customized result.
It also offers a single command to generate your code from your schema.

This package intents to be more generic and offer it's users to customize the results and create custom generated code from their schema and operations. 
At the moment, `apollo-codegen` aims to generate typescript, flow and swift only.

**Comment by altschuler** [comment]
Thank you! That clears things up. This might be a good addition to the readme.

**Comment by zephraph** [comment]
Also, apollo-codegen is focused more around queries. This project generates useful code for schemas as well which helps to provide types for your resolvers. Super, super useful.

**Comment by dotansimha** [comment]
Added to README :) Thanks @altschuler @zephraph !
