### ISSUE TITLE
"Unexpected GraphQL type definition" - unsure how to resolve

### ISSUE THREAD

**Issue by kgoggin** [dotansimha/graphql-code-generator#1273]
**Describe the bug**
I'm working on a [plugin for generating ReasonML types](https://github.com/kgoggin/graphql-codegen-reason). Everything works while I'm working within the plugin's repo, where I've set up a test schema. But, when I try to use the plugin in my actual codebase, I get the following error:

```
Unexpected GraphQL type definition: Query (As string: Query).Please check that you are importing only one instance of the 'graphql' package.
```

I tracked the error to figure out it was getting thrown [here](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/src/schema/schema-to-template-context.ts#L65). I've experienced other issues in the past where GraphQL fails the `instanceOf` check and been able to resolve them by using yarn's `resolve` feature to lock down the GraphQL version, but that hasn't worked for me in this case.

I'm unsure where to go from here with trying to troubleshoot the error. I'm unclear how `Query` is getting set as the value for the `graphQlType` argument in the referenced lines of code, and I'm not sure how that indicates that there are multiple instances of `graphql` in play. I'd really appreciate any guidance on how to proceed!

**To Reproduce**
I'm able to reproduce when using my plugin in a different repo that already has `graphql` as a dependency. It's not specific to the schema at all, as I actually tested the same schema in my plugin repo and was able to get it to generate just fine.

**Comment by forclan** [comment]
I have met the same issue.
When I develop a plugin and use `npm link` to test package locally, the error accours, and this seems to be something with `npm link`. [see here](https://medium.com/@vcarl/problems-with-npm-link-and-an-alternative-4dbdd3e66811)

My solutaion is using `npm pack` and `npm install PACKAGE` instead of `npm link`.

**Comment by dotansimha** [comment]
@kgoggin thank you for opening this issue.
As @forclan said, it's not an issue with graphql-code-generator. The cause of this error is the fact that you can't have multiple instances of `graphql` under the same project.
The current solution for it is to use `npm pack` and then `npm install`, because that's the only way to make sure to get only the compiled code and not all the dependencies. 

I think, but not sure, that if you specify `NODE_ENV=production`, then `graphql` should avoid throwing this kind of error, I think it worth a try.
