### ISSUE TITLE
Nullable fields with typescript

### ISSUE THREAD

**Issue by altschuler** [dotansimha/graphql-code-generator#138]
I'm having a recurring issue with how nullable fields are emitted in typescript. The current way is to use `field: <type> | null` which I suppose is theoretically correct, but in practice it doesn't always play well since typescript will complain that some nullable field is missing (because it's undefined and not actually null). The more typescriptish way would be to make it an optional field like `field?: <type>`, but I'm not sure if that would have other implications.

**Comment by dotansimha** [comment]
It makes sense. 
Actually it's a workaround for an issue that existed a long time agon in `apollo-client` that forced null value for nullable types.
I guess that using `?` is more ts-ish. 
I will fix it soon.

Thank you @altschuler

**Comment by tkogahf** [comment]
This is my opinion, but I think avoidOptionals.field should be true by default because when you query nullable fields, GraphQL never responds "undefined" type. (Nullable inputValue in GraphQL, on the other hand, is optional and should use ? in typescript)

I use config below, and it works perfect.
 config:
   avoidOptionals:
     field: true

This code generator is a big time saver! Thank you.
