### ISSUE TITLE
how to add object in code generator?

### ISSUE THREAD

**Issue by lim-enhui** [dotansimha/graphql-code-generator#1394]
In my send-message.graphql.. I added this..

```graphql
mutation sendMessage($chatid: String!, $data: {
  content: String!
  createdAt: Int!
  uid: String!
}) {
  sendMessage(chatid: $chatid, data: $data)
}
```
Failed to generate [object Object]

attempted 
```graphql
mutation sendMessage( $chatid: String!, $data: CreateMessageInput!) {
  sendMessage(chatid: $chatid, data: $data)
}

input CreateMessageInput {
  content: String!
  createdAt: Int!
  uid: String!
}
```

i could not find helpful documentation for this...

in my graphql backend:

```graphql
type Mutation {
  sendMessage(chatid: String, data: CreateMessageInput!): String!
}

input CreateMessageInput {
  content: String!
  createdAt: Int!
  uid: String!
}
```

**Comment by dotansimha** [comment]
Hi @lim-enhui ! 
In general, I think your API of `sendMessage` should return the newly created message object, instead of `String!`. It's a better way to use GraphQL and it's powerful features.
I didn't understand what do you mean by adding an object? how do you use the codegen? can you please add your `codegen.yml` file? Please try to follow our template for bug reports/questions.

**Comment by lim-enhui** [comment]
yes i am using code gen. it just gives me error. do you have an example to implement an object?

**Comment by dotansimha** [comment]
@lim-enhui Please share your yml config file, your schema and operation.

**Comment by kamilkisiela** [comment]
H1 @lim-enhui :) I think I know what you're trying to achieve here. 

When you define this on the server:

```graphql
type Mutation {
  sendMessage(chatid: String, data: CreateMessageInput!): String!
}

input CreateMessageInput {
  content: String!
  createdAt: Int!
  uid: String!
}
```

You need to use `CreateMessageInput` on the client too, but you don't have to define it anywhere else. So in order to consume the `sendMessage` mutation in the app you do:

```graphql
mutation sendMessage($chatid: String!, $data: CreateMessageInput!) {
  sendMessage(chatid: $chatid, data: $data)
}
```

GraphQL understands how `$data` should look like.

Could you correct me if I'm wrong? We're here to help you but we will eventually close the issue in few days if we don't get any response from you.

**Comment by dotansimha** [comment]
@lim-enhui, I'm closing this issue, feel free to re-open a new issue if it's still relevant.
