### ISSUE TITLE
[typescript-operations] 1.0 break namespace pattern

### ISSUE THREAD

**Issue by ticruz38** [dotansimha/graphql-code-generator#1583]
I updated to 1.0, everything is fine, except that the namespace pattern has been abandonned.
Is there any way to get it back ? as my project rely a lot on graphql-code-generator and is quite big already, it is going to be a pain to change all my imports to match the new pattern.
to be clear, I used to do:
```
compose(
  CurrentUser.HOC({})
)(UserComponent)
```
and now I need to write
```
compose(
  withCurrentuser({})
)(UserComponent)
```

**Comment by dotansimha** [comment]
Hi @ticruz38,
We're aware that the changes in 1.0 are breaking, but we had to introduce breaking changes in order to improve the codegen. 
The reason we abandoned TypeScript `namespace`s is the fact that not all TypeScript compilers supports it (babel-typescript does not support it - https://github.com/babel/babel/issues/8244). 
Also, the reason we needed `namespace`s before was because we generated multiple TypeScript `interface`s and we wanted to group them to avoid conflicts. 
Since 1.0, we are generating only a single TypeScript `type` per GraphQL operation, so we no longer need to group it inside a namespace. 

If you wish, you can create a custom plugin that creates those namespaces and point it to the generated type, and you'll get a backward compatibility:

```typescript
import { OperationDefinitionNode, GraphQLSchema, concatAST, Kind } from 'graphql';
import { Types } from '@graphql-codegen/plugin-helpers';
import { BaseVisitor } from '@graphql-codegen/visitor-plugin-common';

export function plugin(schema: GraphQLSchema, documents: Types.DocumentFile): string {
    const baseVisitor = new BaseVisitor({}, {});
    const allAst = concatAST(
        documents.reduce((prev, v) => {
        return [...prev, v.content];
        }, [])
    );
    const operations = allAst.definitions.filter(d => d.kind === Kind.OPERATION_DEFINITION) as OperationDefinitionNode[];

    return operations.map(operation => {
        const name = baseVisitor.convertName(operation.name.value);

        return `export namespace ${name} {
            export type HOC = with${name};
        }`
    }).join('\n');
}
```

**Comment by ticruz38** [comment]
I tried on my project and it works, however, gql-gen seems to struggle to read the custom plugin in typescript, so I transformed it in pure js. Could not figure out how to make it read typescript even with ts-loader/register

I added all custom types generated by operation under the namespace, to have full retro-compatibility like this:
```
return `export namespace ${name} {
            export const HOC = with${name};
            export type ${operationName} = ${name + operationName};
            export type Props = ${name}Props;
            export const Component = ${name}Component;
            export const Document = ${name}Document
        }`;
```
it would be nice to have this plugin added by configuring codegen.yml with a new entry (withNamespace for example) and document the fact that it's not supported by babel-typescript

Thanks for the great work and your quick answer!

**Comment by dotansimha** [comment]
@ticruz38 You should install `ts-node` and `typescript` and make sure that you have a valid `tsconfig.json`. But plain JS is also great. I'm glad it helped you.
