### ISSUE TITLE
Feature request: extensibility 

### ISSUE THREAD

**Issue by blackxored** [dotansimha/graphql-code-generator#162]
If we really want to be able to extend this, a few big things are missing IMHO:

* Gives us the AST. Directives support is cool but if we're going to be generating UI we probably need the AST or some kind of higher level constructs. Example case: build ListView components from Relay connections.
* Allow pointing to a Github repo or npm-package for extra templates/generators.
* Improve testing support for people building generators.

What do you guys think?

**Comment by dotansimha** [comment]
Hi @blackxored !
Can you please provide an example for usage with the AST, and how you want to use it? do you mean just the basic output of graphql's `print`? 

Also, I wonder how to support extensibility for template/generator from NPM package, maybe try to `require` the name of the generator (from the CLI value) ?

And regarding the support for people building generators - I am working on a simple dev tool for creating templates and shows you the output in real-time :)

**Comment by zephraph** [comment]
That last idea sounds really interesting... I'm excited to see what you come up with!

**Comment by dotansimha** [comment]
The current roadmap is:

- Remove the concept of `single` / `multiple` / `project` and replace it with a pure function that gets the compilation context and returns an array of `{ filename: string, content: string}`.
- Move generators to a separate NPM packages: each package exports the pure function, and each generator will have it's own dependencies (no need for the `code-gen-generators`) now.
- The compiler will no longer use `handlebars` and allow the external package to load it's own processor (related to https://github.com/dotansimha/graphql-code-generator/issues/157).

The CLI will accept the same parameter for the template name (`--template`) but now instead of looking for hardcoded templates, it will try to `require(..)` it and load it's default export and execute it as the pure output processor function.

**Comment by zephraph** [comment]
Well, I mean, it sounds cool. It also sounds like another major release w/ breaking changes.

**Comment by dotansimha** [comment]
So at the moment, it's much easier to extend and create custom templates, either with Handlebars or without it :)
