### ISSUE TITLE
MongoDB types are not emitted, using apollo-server

### ISSUE THREAD

**Issue by ScreamZ** [dotansimha/graphql-code-generator#1765]
**Describe the bug**

Hi,

I'm using apollo-server with the following implementation, everything get emitted but nothing for mongodb types.

**To Reproduce**

Everything can be found by cloning this repo on master branch : https://github.com/ScreamZ/codegen-sample-bug

Then run 
- `yarn`/ `npm i`
- `npm start`
- (postinstall should generate proper output, but in case not, just run tsc from `node_modules/.bin/tsc`

**Expected behavior**

I want the mongodb plugin to work…

**Environment:**

- OS: 

```
OSX Mojava 10.14.3
```

- graphql-codegen/

```json
"dependencies": {
    "apollo-flash": "^1.0.0-rc1",
    "apollo-server-express": "^2.4.8",
    "babel-runtime": "^6.26.0",
    "express": "^4.16.4",
    "graphql": "^14.2.1",
    "mongodb": "^3.2.3"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^1.1.1",
    "@graphql-codegen/typescript": "1.1.1",
    "@graphql-codegen/typescript-mongodb": "1.1.1",
    "@graphql-codegen/typescript-resolvers": "1.1.1",
    "@types/express": "^4.16.1",
    "@types/graphql": "^14.2.0",
    "@types/jsonwebtoken": "^8.3.2",
    "@types/mongodb": "^3.1.25",
    "@types/node": "^10.5.4",
    "prettier": "1.16.4",
    "tslint": "^5.13.1",
    "typescript": "^3.4.4"
  }
```
- NodeJS: 
```sh
$ node -v
v11.0.0
```

Thank you for your feedback :)

Regards

**Comment by dotansimha** [comment]
Thank your for reporting it, @ScreamZ , I'll take a look soon.

**Comment by dotansimha** [comment]
Hi @ScreamZ , sorry for the delay.
You are using http endpoint to load your schema, and that's an issue with mongodb plugin because GraphQL exposes Introspection JSON from the http endpoint, and introspection does not include the GraphQL directives.
You should use a static schema for the codegen in order to get it working, so you can either `.graphql` files and load them (with `graphql-import-node`), and then use `src/schema/*.graphql` as your schema, or create a file that `export default` a `GraphQLSchema` object (with `require: ts-node/require` if you are using TS).
