### ISSUE TITLE
 Type mismatch on returning promise with `graphql-code-generator` and `prisma` 

### ISSUE THREAD

**Issue by devautor** [dotansimha/graphql-code-generator#1793]
I am getting an error with `graphql-code-generator` and `prisma` type mismatch on returning promise.

That is, for this field resolver:
```
customer: async (root, args, context) => {
    try {
      return await context.prisma.customerCartItem({ id: root.id }).customer();
    } catch (error) {
      console.error(error);
    }
  },
```
I am getting this error:
```
src/resolvers/cartResolvers.ts:25:3 - error TS2322: Type '(root: CustomerCartItem, args: {}, context: IContext) => Promise<Customer>' is not assignable to type 'Resolver<Customer, CustomerCartItem, IContext, {}>'.
  Type '(root: CustomerCartItem, args: {}, context: IContext) => Promise<Customer>' is not assignable to type 'ResolverFn<Customer, CustomerCartItem, IContext, {}>'.
    Type 'Promise<Customer>' is not assignable to type 'Customer | Promise<Customer>'.
      Type 'Promise<import("G:/graphql/prod/graphql-server/src/generated/prisma-client-ts/index").Customer>' is not assignable to type 'Promise<import("G:/graphql/prod/graphql-server/src/generated/resolvers-types").Customer>'.
```

**From what I get, `prisma` returns `interface CustomerPromise` [`export interface CustomerPromise extends Promise<Customer>, Fragmentable `] for chained query (one used), while `Promise<Customer>` is expected as return expression by `graphql-code-generator`. How to fix that?**

1. Is there any example of using `prisma` with this tool? 
2. I was doing good until I used `context` correctly (only then this error was shown, which is understandable since the error is on return types only, i.e. returning using `prisma`)?

**Comment by dotansimha** [comment]
Hi @devautor ! It looks like there are two types for `Customer` - one generated by Prisma, and one generated by the codegen, and that's the reason for the mismatch. 

It's very difficult to investigate your use case this way, can you please create a small repository with an reproduction of it? Because we need your schema, environment and codegen configuration in order to reproduce it locally. 

At the moment I can just guess, that you need to pass `mappers` configuration for the `typescript-resolvers` plugin, and map your GraphQL type `Customer` to the one generated by Prisma, and this way it will make sure to generate a signature based on that type.

**Comment by devautor** [comment]
Hello @dotansimha Thank you for your reply and kind patience! I'd like to ask you for a few hours where I could get a repo working for you to inspect :)

**Comment by devautor** [comment]
Hello @dotansimha I have reproduced the issue here: https://github.com/devautor/graphql-code-generator-issue-1793-repro
Please let me know if it misses something or if it doesn't work for you! :)

**Comment by dotansimha** [comment]
@devautor 
First, start by loading your schema staticaly, create a file called `src/codegen-schema.ts` with:

```ts
import typeDefs from "./schema";
import { makeExecutableSchema } from 'graphql-tools';

export default makeExecutableSchema({
  typeDefs,
});
```

Now, let the codegen to load your schema statically, and it will be easier to test it because you don't need the server running:

```yml
schema: src/codegen-schema.ts
```

You can use `mappers` (https://graphql-code-generator.com/docs/plugins/typescript-resolvers#mappers-object) to map the resolver of `Customer` to Prisma `Customer`:

```yml
config:
      mappers:
        Customer: ./prisma-client-ts#Customer
```

You need to do that for all the possible types you are going to return. You can also use the generic option of the resolvers instead of `mappers`, but you still need to find the models types of Prisma methods and map it.

Oh and also, you'll need to match `Maybe` of the `codegen` to the one by Prisma by adding to the `config`:

```yml
maybeValue: "T | undefined | null"
```
