### ISSUE TITLE
Watch mode builds should trigger selectively, only for GraphQL source files

### ISSUE THREAD

**Issue by slikts** [dotansimha/graphql-code-generator#1797]
Currently, if JS/TS source files are included as sources for the generator, the watch mode build gets triggered on any change in any file, most of which, in a typical scenario, won't contain GraphQL, and the generated files in turn needlessly trigger other watch processes like webpack. I've worked around this issue by scanning the source text for the presence of "gql`" template tag opening and caching the matches, but a more robust solution would extract the tags from the AST, which I suspect would still yield acceptable performance.

**Comment by dotansimha** [comment]
Hi @slikts
I tried to figure out how to approach this issue, but I think the main problem it the user itself. 
At the moment, the watcher uses the exact glob expression as that you provided - if's too broad and contains invalid files - we can't really do anything about it. 
I think the other option is to add a file to the list of watched files only if the file is actually has been read - but then we skip all possible file creations/deletions. 

I'm keeping it as is, which means (after these changes: https://github.com/dotansimha/graphql-code-generator/pull/2359): we watch the config file, and every glob/file specified through `schema` or `documents`, even it it's a glob expression. 

Please let me know if you have an idea for workaround this. 

Also, since this issue, a lot has changed in terms of performance, so you might want to check the latest version ;)
