### ISSUE TITLE
Export (Flow) type for each possible variant of a union result as a separate type

### ISSUE THREAD

**Issue by FokkeZB** [dotansimha/graphql-code-generator#1870]
**Is your feature request related to a problem? Please describe.**

For this query:

```graphql
query findStuff {
  search(term: "foo") {
     ... on User {
      id
      username
    }
    
    ... on ChatMessage {
      id
      content
    }
  }
}
```

Based on the following schema:

```graphql
schema {
  query: Query
}

type Query {
  search(term: String!): [SearchResult!]!
}

union SearchResult = User | ChatMessage

type User {
  id: ID!
  username: String!
}

type ChatMessage {
  id: ID!
  content: String!
}
```

I get the following Flow types:

```javascript
export type FindStuffQuery = ({ __typename?: 'Query' } & { search: Array<(({ __typename?: 'User' } & $Pick<User, { id: *, username: * }>) | ({ __typename?: 'ChatMessage' } & $Pick<ChatMessage, { id: *, content: * }>))> });
```

While I'd like:

```javascript
export type FindStuffQuery_User = ({ __typename?: 'User' } & $Pick<User, { id: *, username: * }>);
export type FindStuffQuery_ChatMessage = ({ __typename?: 'ChatMessage' } & $Pick<ChatMessage, { id: *, content: * }>);

export type FindStuffQuery = ({ __typename?: 'Query' } & { search: Array<(FindStuffQuery_User | FindStuffQuery_ChatMessage)> });
```

So that I can use it in:

```javascript
function handleUser(obj: FindStuffQuery_User) {
  console.log(obj.username);
}

function handleContent(obj: FindStuffQuery) {
  if (obj.__typename === 'User') {
    handleUser(obj);
  }
}
```

Instead of either manually needing to define `FindStuffQuery_User` or repeat the `__typename` check everywhere I use the object:

```javascript
function handleUser(obj: FindStuffQuery) {
  if (obj.__typename !== 'User') {
    return;
  }
  console.log(obj.username);
}

function handleContent(obj: FindStuffQuery) {
  if (obj.__typename === 'User') {
    handleUser(obj);
  }
}
```

I know - from discussion via email - that this was once (< 1.0) in place for the Typescript generator, but got pulled because it generated too many types and possible collisions.

I challenge that, as:

- This only generates additional types for queries that return unions or interfaces.
- The expected `FindStuffQuery` re-uses the individual types, so it's not that much additional code.
- By namespacing the types with the query Flow type name, there should be no collisions between queries.

**Comment by dotansimha** [comment]
Hi @FokkeZB ! 
Before 1.0 we had a similar solution for TypeScript, but it was very hard to maintain, because of mismatches and conflicts of identifiers. That was the main reason for moving to use `Pick<>` for a base type, and generate a complete type per each query.

If you wish to get an intermediate types, you can create them by yourself manually:

```js
export type FindStuffQuery_User = $ElementType<FindStuffQuery, 'search'>
```

Or, you can create your own plugin that generates these intermediate types for you, for TypeScript we have a similar plugin called `typescript-compatibility` (it generates TypeScript `namespace`s, but it can easily replaced with a `Name_TypeName` syntax). 

I know that working with unions makes it a bit more complicated, and that's why in TypeScript plugins we used some utility method that extracts a inner type according to a predefined fields (in our case, `__typename`), but I'm not sure how to do that in Flow. 

In TS, we did that by adding the following type:
```ts
type A = { __typename: "A", a: string };
type B = { __typename: "B", b: string };
type U = A & B;

type DiscriminateUnion<T, U> = T extends U ? T : never;

type OnlyA = DiscriminateUnion<U, { __typename: 'A' }>;
```

Our knowledge of Flow is a bit limited, so we welcome the community to help us improve the Flow plugins (so we always welcome PRs ;) ).

**Comment by FokkeZB** [comment]
@dotansimha I played some with https://flow.org/en/docs/types/utilities/ and https://flow.org/try/ but I don't think you could create something like `DiscriminateUnion` in Flow.

I'll have to icebox this for now - also since we're looking into moving to TS :D
