### ISSUE TITLE
Can I use this tool for Golang projects?

### ISSUE THREAD

**Issue by akashbdj** [dotansimha/graphql-code-generator#1881]
Hi,

Is it possible to use this tool for Golang Projects? If yes, could you please point me to some resources on how to get started with it? 

Does writing a new template work?

Thanks for reading,
Akash

**Comment by dotansimha** [comment]
Hi @akashbdj ! 
Currently we don't have any Golang plugins available, mainly because we are not familiar with Go and it's environment. 
There is an open issue for this one: https://github.com/dotansimha/graphql-code-generator/issues/298 , so I'm closing it.
We are welcome the community to create any plugin according to their needs, and we'll be happy to help you on our end.

**Comment by akashbdj** [comment]
Could you please tell me "How to write a plugin" for it? I'd be happy to work on it.

**Comment by dotansimha** [comment]
Sure, @akashbdj , you can find it in our website: https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin 

Feel free to contact us if you need any assistance.
