### ISSUE TITLE
Plain JavaScript plugins?

### ISSUE THREAD

**Issue by Thebigbignooby** [dotansimha/graphql-code-generator#2008]
I like the idea of code generation, actually your issue on Prisma's "graphqlgen" is what brought me here.

However, neither tool gives the possibility of generating JavaScript, I'm stuck with having to choose between TypeScript and Flow

Would it be possible to add an option for generating resolvers in JavaScript ?
If not, then could you explain why ?

**Comment by dotansimha** [comment]
Hi @Thebigbignooby 

Can you please elobarate on your needs? 

We are generating code for TypeScript and Flow because those are JavaScript supersets that supports types, so we are using the strongly-type principle of GraphQL and transforming it into language types.

JavaScript by itself does not support types, so that's why we don't have plugins for it.

Note that we do have plugins that generates other type of outputs (JSON, Java and more).

If you have an idea for a new plugin, we can definitely consider to add it (or, you can write it yourself if you wish).

**Comment by dotansimha** [comment]
Hi @@Thebigbignooby, I'm closing for now. Feel free to reopen if you have more questions.
