### ISSUE TITLE
Introduce generic replacement for old SchemaToTemplateContext 

### ISSUE THREAD

**Issue by wtrocki** [dotansimha/graphql-code-generator#2151]
GraphQL code generator is not offering generic schemaToTemplateContext that can be useful for plugin creators to generate visitors. Currently to create plugin developers will need to figure out their own visitor patterns and elements from the schema. For most of the cases, the generic visitor creating Type/Fields objects would work nicely. 

Previous versions supported that by `schemaToTemplateContext` method

**Comment by dotansimha** [comment]
Hi @wtrocki , 
We removed `schemaToTemplateContext` because it's not longer necessary to make an additional transformation to the schema or operations. 
Currently our plugins are using the AST of the schema and operations, and uses visitor pattern to transform it. It makes it easier to develop and maintain. 
We provided a set of pre-defined visitors you can use to write your plugin faster (see https://graphql-code-generator.com/docs/custom-codegen/using-visitor). You can also use https://astexplorer.net/ which makes it much easier to deal with AST.

**Comment by wtrocki** [comment]
Thank you. This is what I was looking for
