### ISSUE TITLE
Prevent "export" directive in generated types?

### ISSUE THREAD

**Issue by dalindsey** [dotansimha/graphql-code-generator#2246]
Is there a way to prevent the types from having the "export" directive prefix after generation in the config or otherwise?

To be clear, I am trying to having export directives for top-level types like enum, but omit them for types/interfaces.

**Comment by dotansimha** [comment]
@dalindsey can you please explain and add an example? I couldn't understand what's your use-case.

**Comment by dotansimha** [comment]
@namesphill
@dalindsey 

I added this feature in https://github.com/dotansimha/graphql-code-generator/pull/2278, you can set `noExport: true` in your config - note that this will effect only `typescript` and `typescript-operations` (because other plugins needs import or creates variables, so they cant be located in `.d.ts` file). 

Note that if you plan to use `.d.ts` extension, you need to set `enumsAsTypes: true`.

**Comment by dotansimha** [comment]
Available in 1.5.0 🎉
