### ISSUE TITLE
 Unexpected Type Generation

### ISSUE THREAD

**Issue by polRk** [dotansimha/graphql-code-generator#2281]
schema.graphql
```graphql
type contact {
    avatar: String
    created_at: timestamptz!
    email: String
    id: uuid!
    lang: String
    name: String!
    phone: String
    updated_at: timestamptz!
}
```

Query
```typescript
export const contactFragment = gql`
    fragment Contact on contact {
        id
        created_at
        updated_at
        name
        avatar
        email
        phone
        lang
    }
`
```

And generated type

```typescript
export type ContactFragment = Pick<
  Contact,
  | 'id'
  | 'created_at'
  | 'updated_at'
  | 'name'
  | 'avatar'
  | 'email'
  | 'phone'
  | 'lang'
>
```

It should generate like this
```typescript
export type ContactFragment = Contact
```

**Comment by dotansimha** [comment]
@polRk 
GraphQL allow you to choose a selection set - so you can choose your fields. 
The base types generated by `typescript` plugin are a TypeScript representation of the entire GraphQL type (as it described in your GraphQL schema). 
Then, the `typescript-operations` is a TypeScript representation of your queries/mutations/subscriptions/fragments. Because GraphQL allow you to choose your fields - the codegen will use the base type and will `Pick<>` the relevant fields from the base type, in order to create a new type that reflects your selected fields. 
At the moment, the codegen doesn't optimize the use-case of picking all fields - it just does `Pick<>` for all fields.
