### ISSUE TITLE
weird effects with schema-ast with `includeDirectives: true`

### ISSUE THREAD

**Issue by leebenson** [dotansimha/graphql-code-generator#2439]
With the [schema-ast plugin](https://graphql-code-generator.com/docs/plugins/schema-ast), I'm noticing odd behaviour when configured with `includeDirectives: true`.

Given these source files:

**schema.graphql**
```gql
schema {
  query: Query
  mutation: Query
}
```

**types.graphql**
```gql
type Query {
  test: String
}

type Mutation {
  test: String
}
```

**ping.graphql**
```gql
extend type Query {
  ping: String!
}
```

Omitting `includeDirectives` (default) generates:

```gql
schema {
  query: Query
  mutation: Query
}

type Mutation {
  test: String
}

type Query {
  test: String
  ping: String!
}
```

But using `includeDirectives: true` omits `schema`, and adds lots of whitespace:

```gql



type Query {
  test: String
  ping: String!
}










type Mutation {
  test: String
}
```

**Comment by dotansimha** [comment]
Hi @leebenson ! 

The `includeDirectives` effects the behaviour not only in terms on directives, vut it uses `graphql-toolkit` to print the schema, instead of `graphql` (because `graphql` removes directives while printing). 
`graphql-toolkit` scans the schema manually and prints each object by itself, and includes the directives. It also skips the `schema { ... }` when you are using the default types names (`Query`/`Mutation`). 

The output with the spaces is a bit weird, but I think add a hook with prettier (https://graphql-code-generator.com/docs/integrations/prettier) will solve this at the moment.

**Comment by leebenson** [comment]
gotcha, makes sense, thanks!
