### ISSUE TITLE
include other .yml files from codegen.yml

### ISSUE THREAD

**Issue by shiatsumat** [dotansimha/graphql-code-generator#2480]
When I want to specify TypeScript types for custom scalars in GraphQL, I basically have to write the type information in codegen.yml (like `config: {scalars: ...}`) along with other fixed configurations.

Since the concrete representations for custom scalars may change frequently, I came to feel like separating out the type specifications for custom scalars from codegen.yml.
But there is no way to include other .yml files from codegen.yml. Since codegen.yml does allow embedding environment variables, I thought of writing type information into .env file, but that's not at all beautiful.

For this reason, I definitely hope that codegen.yml can include other .yml files. For example, we can possibly adopt syntax like `!include file.yml`.

**Comment by dotansimha** [comment]
Hi @shiatsumat ! 

Since the latest version of the codegen, you can specify a single file that includes all your scalars types. See this: https://github.com/dotansimha/graphql-code-generator/pull/2418 

Can you please explain your use case? Why does your scalars changes frequently? Because it sounds like something that very hard to maintain (in terms of usage and implementation). 

We currently support the basic yml spec, so it doesn't have the ability to import from other files, but it does allow to use placeholders which might help you (see https://stackoverflow.com/questions/2063616/how-to-reference-a-yaml-setting-from-elsewhere-in-the-same-yaml-file).

Also, note that the configuration files doesn't have to be a `.yml` file - you can also use `.json` or even `.js` file that exports JavaScript object that you can build in runtime (and the you can include any file by yourself). 

Please let me know if that works for you :)

**Comment by shiatsumat** [comment]
Thank you for kind comments!

I didn't know about the new feature #2418. Specifying TypeScript module sounds great and better manageable than the "include .yml" approach. Thank you for fantastic features!

I am going to use the `scalars: [module_path]` notation, but it seems that there remains some bugs for this feature, so I'll report it on #2418.
