### ISSUE TITLE
ID Scalar is incorrectly typed

### ISSUE THREAD

**Issue by n1ru4l** [dotansimha/graphql-code-generator#2588]
**Describe the bug**

When you return a number as an `ID` type in a resolver, it causes a typescript error. However, `graphql.js` does also accept returning numbers which are then automatically cast to strings.

See https://graphql.github.io/graphql-spec/draft/#sec-ID

TL;DR:

ID as operation argument/return type from resolver -> string or number
ID as operation selection set value -> string

**Comment by ardatan** [comment]
@n1ru4l I think it is correct right now because if you have a different type than string in your entity(parent) type, you can use mappers to define it like below;
```ts
export interface UserEntity {
    id: number;
   name: string;
}
```
```gql
type User {
  id: ID
  name: String
}
```
```ts
export const Query: QueryResolvers = {
   user(_, { id }) => ({ id: 2, name: 'TestUser' }),
}
```

**Comment by n1ru4l** [comment]
> So in that case, it should be fine, because if we change ID to string | number, it wouldn't be consistent with client which is always string.

Wouldn't it be possible to distinguish between resolver return `ID` and client-consumed `ID`?

**Comment by ardatan** [comment]
@n1ru4l We can do that but we use those generated types in client as well. They shouldn't be used as parent types in my opinion because the data coming from another source is generally different than the one fetched by client. I think we should keep that and you should use `mappers` as I said.
@dotansimha What do you think?

**Comment by dotansimha** [comment]
I think we can generate different types for client and server, that shouldn't be a problem. 
I think the codegen assumes that `ID` is `string` in GraphQL, but the actual real value is a number or a string. So I think the should maybe change it in the codegen, even if it's a breaking change for some developers (because it caused by an actual bug in the codegen).

**Comment by dotansimha** [comment]
The actual default value of the `ID` scalar should be `string | number`, to match the implementation of the scalar in `graphql.js`: https://github.com/graphql/graphql-js/blob/730f5cc6e0c7b7994cb11fe1a9785700fa4dc5db/src/type/scalars.js#L256 

@n1ru4l @ardatan @kamilkisiela what do you think? Do you think it will cause any breaking changes?

**Comment by n1ru4l** [comment]
https://github.com/graphql/graphql-js/blob/730f5cc6e0c7b7994cb11fe1a9785700fa4dc5db/src/type/scalars.js#L239-L247

ID as Input -> String or Number
ID as Output -> String

**Comment by dotansimha** [comment]
@n1ru4l you are right. I guess the best solution for that is to add `inputScalars` config and have a default `ID = number | string` there.

**Comment by dotansimha** [comment]
Related: https://github.com/dotansimha/graphql-code-generator/issues/2684

**Comment by tslater** [comment]
@dotansimha  Do you have any plans for this? We got started on using code-gen but then were blocked by this and a couple other things. Seems like having two types of scalars is the way to go for most ID implementations. Ours is even more complicated because we have some Binary and some Int type IDs under the hood...all client ID types are opaque strings and relay compatible...so they include the type as well. So args are typically deserialized as a `{ type: enum, id: Buffer()}  | { type: enum, id: number}` and then outputs can are `Buffer() | number`  (to use some pseudocode). Of course for a given GraphQL type the ID type is singular/static. We can map to maybe get around telling codegen which types are which...but we still need different inputs and outputs...and my understanding is that we would want parent to be the output type as well...since that is before scalars are fully resolved/serialized.

**Comment by dotansimha** [comment]
@tslater Hi! I really want to see a solution for this one. But I might need the community assistance here, due to lack of time :(

**Comment by eddeee888** [comment]
This is available in this release: https://github.com/dotansimha/graphql-code-generator/pull/9355
