### ISSUE TITLE
info argument for Resolver as optional

### ISSUE THREAD

**Issue by pradospeedsheld** [dotansimha/graphql-code-generator#2632]
Hi
Is there a config in yml or any other way where I can have info argument as optional in the generated types from resolvers?
I am having trouble to write some tests where it's complaining about not providing info but somehow it doesn't complain in the actual Resolver function for Query.
Thanks

**Comment by dotansimha** [comment]
@kamilkisiela can you please take a look?

**Comment by kamilkisiela** [comment]
TypeScript doesn't complain in the actual resolver function because all arguments are there, you just don't use them. The resolver function has 4 arguments that are always defined so if you want to test the resolver function, TypeScript requires from you to provide all, even `GraphQLResolveInfo`.

That's 100% correct because that's what graphql expects and TS wants to make sure you pass everything correctly.

Of course, you as a developer knows that the resolver function uses only first two arguments, no context, no info so from your perspective only those two are non optional.

Please take a look at this issue:
https://github.com/dotansimha/graphql-code-generator/issues/2124#issuecomment-517210839

@dotansimha I guess we could export a similar function in `typescript-resolvers` package so everyone could use it and it could be always up to date with codegen's output.

**Comment by dotansimha** [comment]
It can be done now with `optionalInfoArgument: true` (in recent versions)
