### ISSUE TITLE
Multi Dimensional Arrays in Typescript

### ISSUE THREAD

**Issue by mattcroberts** [dotansimha/graphql-code-generator#329]
For a given schema

```
enum Player {
    NAUGHT
    CROSS
}

type GridItem {
    id: ID!
    player: Player
}

type Grid {
    id: ID!
    gridItems: [[GridItem!]!]!
    currentPlayer: Player!
    winner: Player
    isFinished: Boolean!
}
```

The following types are generated

```
export interface Grid {
    id: string;
    gridItems: GridItem[];
    currentPlayer: Player;
    winner?: Player | null;
    isFinished: boolean;
}

export interface GridItem {
    id: string;
    player?: Player | null;
}

export enum Player {
    NAUGHT = "NAUGHT",
    CROSS = "CROSS"
}
```

Notice how Grid.gridItems is a 2d array in the schema but 1d in the types.

**Comment by dotansimha** [comment]
@mattcroberts thanks for reporting it! it's definitely a bug. Will try to fix soon :)

**Comment by lostpebble** [comment]
Has there been any movement on this? I've run into this and my types are auto-generated from my GraphQL files... its quite an issue because its hard to split out that type temporarily because they're all connected in my GraphQL schema and if I manually change them to make them correct, they'll still be over-written each time I generate new types.

**Comment by lostpebble** [comment]
Great to hear @dotansimha ! Much thanks 🙂
