### ISSUE TITLE
error with programmatic usage in a React app bundled with webpack

### ISSUE THREAD

**Issue by wawhal** [dotansimha/graphql-code-generator#3357]
I am trying to integrate graphql-codegen in a dashboard. It is a React app bundled with webpack. When I try to import `@graphql-codegen/core`, it throws me a bunch of errors saying webpack cannot resolve the node dependencies.

I cannot show the exact repro. But I tried doing this with a simple create-react-app and the problems still come up. Check out the sandbox below.

https://codesandbox.io/s/create-react-app-blank-9zhgl

**Comment by ardatan** [comment]
A reproduction would be great :) Thanks

**Comment by wawhal** [comment]
https://codesandbox.io/s/create-react-app-blank-9zhgl

Also updated the issue description.

**Comment by dotansimha** [comment]
the actual error is: `process.hrtime is not a function`.
It's caused by `relay-compiler` which can only run in a node env at the moment.
To workaround that, you can take a look at the live-demo we have in this repo, it's a react app that uses codegen programatically in-browser. 

See: https://github.com/dotansimha/graphql-code-generator/blob/master/website/live-demo/src/index.tsx#L8-L14

(I think only the workaround for `hrtime` is needed, so try only that at first...)
