### ISSUE TITLE
Add __typename to interface types

### ISSUE THREAD

**Issue by ksrb** [dotansimha/graphql-code-generator#3417]
**Is your feature request related to a problem? Please describe.**

I'm using [`apollo.writeQuery`](https://www.apollographql.com/docs/react/caching/cache-interaction/#writequery-and-writefragment) to generate a relatively complicated local dataset. 

Unfortunately due to the lack of a `__typename` in the generated type `@ts-ignore` has to be used in multiple places in order to access the `__typename` property.

This is a simple example but it illustrates the issue that is occurring without a `__typename` in the generated type:

[**Sandbox**](https://codesandbox.io/s/awesome-mahavira-i31cj?fontsize=14&hidenavigation=1&module=%2Fexample.ts&theme=dark)
```ts
import { User, Animal, CanMove } from "./types";

const cheetah: Animal = { id: "1", nickname: "Speedy", speed: 70 };

const bob: User = { id: "1", name: "Bob", speed: 15 };

function whatCanMove(canMove: CanMove): string {
  // @ts-ignore
  if (canMove.__typename === "User") {
    return (canMove as User).name;
  }

  // @ts-ignore
  if (canMove.__typename === "Animal") {
    return (canMove as Animal).nickname;
  }

  return "Can't move";
}

console.log(whatCanMove(cheetah));
console.log(whatCanMove(bob));
```

**Describe the solution you'd like**
Add option to have `__typename: string` in generated interface types for example:
```yml
config:
  withInterfaceTypename: true/false
```

**Describe alternatives you've considered**
Right now I'm type casting the interface type and using `@ts-ignore` to stop Typescript from failing for example:
```ts
  // @ts-ignore
  if (canMove.__typename === "User") {
    return (canMove as User).name;
  }
```

**Additional context**
Related issues:
- https://github.com/dotansimha/graphql-code-generator/issues/649

**Comment by dotansimha** [comment]
You do have `__typename` there:

```
export type Animal = CanMove & {
   __typename?: 'Animal',
  id: Scalars['ID'],
  nickname: Scalars['String'],
  speed: Scalars['Int'],
};
```

It's an optional field, and you can force it with this configuration: https://graphql-code-generator.com/docs/generated-config/base-visitor#nonoptionaltypename-boolean-default-value-false

Also, what's the use case of using the base types as is? If you are generating client-side code, you should use types that are based on your selection set. In your example, you should use `UserQuery` type in your code, and not the base types.

**Comment by ksrb** [comment]
Admittedly my use case for using `writeQuery` might be a bit narrow/overkill 😅, I'm basically creating a static website for prototype purposes which has no backend backing it right now so I'm creating the entire dataset locally so no queries/fragments have been written yet.

However, perhaps another more valid use case for having typenames in the base type/interface is for utility functions like the `whatCanMove` function, or for example a print/formatting function like:

```tsx
function describeMovers(canMove: CanMove): string { 
  // Based on typename print unique message
}
```

**Comment by ksrb** [comment]
For anyone curious I ended up solving this by creating a union type for all the implementors of the interface something like:

```gql
union Movers =  Users | Animal
```

```tsx
function describeMovers(mover: Mover): string {}
```

Maybe not ideal if you have thousands of implementors...

**Comment by timonweber** [comment]
I would also love to see `__typename` on the base interface as it would allow to process query results independent of the structure of the initial query.

PS: Thanks for your awesome work, @dotansimha!

**Comment by thomasmichaelwallace** [comment]
I initially came to this issue thinking I needed `__typename` for interfaces.

My use case was that I was using the server typings with appsync, and needed to do things like return heterogeneous types all implementing a single interface, but with branching logic on how each type was manipulated.

However, this issue (especially @dotansimha ) challenged me on this, and I realised that what I actually wanted was a union of types implementing each interface; all I was ever going to do with `__typename` on the interface was guard on a discriminated a union.

I saw some mentions (incarnated as possibleTypes?) for client typings, but not for the server-side. So, taking @ksrb 's example, I put this noddy plug-in together:

```js
function plugin(schema /* , documents, config */) {
  const implementingTypes = {};
  const descriptions = {};

  const typeMap = schema.getTypeMap();
  Object.entries(typeMap).forEach(([name, type]) => {
    if (type.description) descriptions[name] = type.description;
    if (!type.getInterfaces) return;
    const interfaces = type.getInterfaces();
    interfaces.forEach(({ name: int }) => {
      const implementing = implementingTypes[int] || [];
      implementing.push(name);
      implementingTypes[int] = implementing;
    });
  });

  const unions = Object.entries(implementingTypes).map(([name, types]) => {
    const plural = `${name}s`;
    const declare = `export type ${plural} = ${types.join(' | ')};`;
    const comment = `/** types implementing ${descriptions[name] || name} */`;
    return [comment, declare].join('\n');
  });
  return unions.join('\n\n');
}

module.exports = { plugin };
```

People coming to this issue; is this useful? Do you want me to publish it? Do I even need to publish it- or have I missed something and the `typescript` plug-in already does this?

**Comment by dotansimha** [comment]
So I had more thinking about this issue, and it's been re-opened now.

This thing is - the `typescript` (and `flow`) plugins are "base" plugins - the types it generates are meant to be used by other plugins, so it could easily consume it.

If the consumer is `typescript-operations`, it will depend on the operation you are using. And in that matter, there is no chance that `graphql` will return the interface name as `__typename`, because fragment will make sure to resolve it to the actual type. Same with unions. 
From the point of view of a GraphQL operation, there will always be `__typename` that points to a GraphQL `type` (and not `interface` or `union`). 
Also, in this case, there is no reason for a developer to use the generated TypeScript `interface` type directly. *Use the types generated for your operation.* That means, that you don't need to use `CanMove` directly. 

If you are using `writeQuery` or a similar method of Apollo, you are basically modifying a specific `query` or `fragment` in the store, which means that you need to use the types for that specific query.
If one of the fields in that query is a GraphQL `interface`, you'll be able to identify the actual type based on `__typename`, because the selection set represents all the possible output types that you can have. 

Let's take for example the following schema: 

```graphql
type Query {
  search(term: String!): [Node!]!
}

interface Node {
  id: ID!
}

type User implements Node {
  id: ID!
  username: String!
  email: String!
}

type Chat implements Node {
  id: ID!
  users: [User!]!
  messages: [ChatMessage!]!
}

type ChatMessage implements Node {
  id: ID!
  content: String!
  user: User!
}
```

And the following GraphQL operations:

```graphql
query test {
  search(term: "1") {
     ... on User {
      id 
      username
    }
    
    ... on Chat {
      id 
    }
  }
}
```  

This will output the following for that operation when you are using `typescript-operations`: 

```ts
export type TestQuery = (
  { __typename?: 'Query' }
  & { search: Array<(
    { __typename?: 'User' }
    & Pick<User, 'id' | 'username'>
  ) | (
    { __typename?: 'Chat' }
    & Pick<Chat, 'id'>
  ) | { __typename?: 'ChatMessage' }> }
);
```

Now, if you want to check what type is `search` field, you should use it as the base, and not the type generated by `typescript`:

```ts
function doSomething(obj: TestQuery['search'][0]) {
  if (obj.__typename === 'Chat') {

  } else if (obj.__typename === 'ChatMessage') {
      
  } else if (obj.__typename === 'User') {
    
  }
}
```

([You can try this here](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCyBDRAjYAeAFQD44BeOAuAHzgDsBXAG0YG4BYAKAHoAqHuAILM42egEtGMALRjacDLQAmcAMb0AzjAgBbOOpUZGGKOoA0cbRjAplWhAAtgYqPJUx6huADdD9YOrgeLk5QSFgEZFQAZQMjEzI4AG9OODgASQARAC49GChZAHNTFLgovMKczXzaIpKAIQgIRmAFHOxG5oVijlS02hgchm1cKG7UgDFGCAwBunph4FHOAF92DhDwaHgkFDgAYXsZhIA5CEVUADIkkrgAfVud4FoMbWAAfhyAcgOZz7G4MSKHIxQzGdQAbU+mU+AF1-hpFuocgIoFAsHgAKrqRZEf6vdTqDAFfzI1Hon4wND+QnE3ErNYbMLbSL7Q6U6lE1DkU7nOBXZI9VL3R7PV4fODfNlUgmcv4lQHA2JgyHQuElFQQfpPWYguIQz5laoFWHw7FQHJYxbdVacRlbCK7Hlc66ChWlJUmFUZE3020cUL2x5wACKfigiASAtSdwekVF7y+ocWiDlguxxhU9lJaMQeCddI4NvWxYD4SDSfDURaUEzKIKAXIUYQi20itBnoN5RqsN9Jc2ZZZlpc3LOlxd0eFcZeCYlQ9TqTduuVUO9asFCKg8bbeshhsKPsFwEsEm3y733bXRbtA92BH8MAriAAasYxBhsM0G0kr32mQ7UHemiPgkAAUJSJDGIrTuKnyPp8cDLCU-J6NWmbZuiYGCqkEGTig8YwXOCE3HycAAApiCoADWmJmuYnyAvBNCfBu8afEQJQAJTUHAmHRkkkFTmKXwUvBiFYSR5FUXgFJ0Qx7GClxNA4bGeHQcJUocsSokkGJHEMhwABm9C0G4YianAigQFEOjADA9iFCBEDYAAVjkgEPmGiCQumNb2LC4IAAwwlxTZiAZPFOc5AB0uFPNOZCkOQkq-CFfqpMscDAIw2IAuFjkuTFKlxa8CVJRS0o0sAnypeJqQlBlWU5WFEUFbF8albOZrVeO0b1SsQA))

But - if the consumer is `typescript-resolvers`, it might be a bit different, because in this case, you want to be able to use the TypeScript `interface` and have `__typename` pointing to the possible types (it works with unions now because we point to the all possible types, but it's not the case with GraphQL interfaces). 
So we can add that option to add `__typename` for that purpose.

*It's important to understand, that if you are using `typescript-operations`, there is not reason to have those. You are using the wrong types.*

**Comment by stijnbernards** [comment]
> I initially came to this issue thinking I needed `__typename` for interfaces.
> 
> My use case was that I was using the server typings with AppSync lambda datasources, and needed to do things like return heterogeneous types all implementing a single interface, but with branching logic on how each type was manipulated.
> 
> However, this issue (especially @dotansimha ) challenged me on this, and I realised that what I actually wanted was a union of types implementing each interface; all I was ever going to do with `__typename` on the interface was guard on a discriminated a union.
> 
> I saw some mentions (incarnated as possibleTypes?) for client typings, but not for the server-side. So, taking @ksrb 's example, I put this noddy plug-in together:
> 
> ```js
> function plugin(schema /* , documents, config */) {
>   const implementingTypes = {};
>   const descriptions = {};
> 
>   const typeMap = schema.getTypeMap();
>   Object.entries(typeMap).forEach(([name, type]) => {
>     if (type.description) descriptions[name] = type.description;
>     if (!type.getInterfaces) return;
>     const interfaces = type.getInterfaces();
>     interfaces.forEach(({ name: int }) => {
>       const implementing = implementingTypes[int] || [];
>       implementing.push(name);
>       implementingTypes[int] = implementing;
>     });
>   });
> 
>   const unions = Object.entries(implementingTypes).map(([name, types]) => {
>     const plural = `${name}s`;
>     const declare = `export type ${plural} = ${types.join(' | ')};`;
>     const comment = `/** types implementing ${descriptions[name] || name} */`;
>     return [comment, declare].join('\n');
>   });
>   return unions.join('\n\n');
> }
> 
> module.exports = { plugin };
> ```
> 
> People coming to this issue; is this useful? Do you want me to publish it? Do I even need to publish it- or have I missed something and the `typescript` plug-in already does this?

This is a good solution for my use case.
Although adding a `__typename` property with all possible type values to all interfaces would be preferrable

**Comment by mjeffryes** [comment]
I want to push this a little further.

The problem that @ksrb encountered is actually a product of the fact that interfaces in GraphQL are sealed (ie. they can only be implemented by a known, finite list of types) whereas interfaces in typescript are not (anyone can extend an interface wherever they like). GraphQL is designed with the expectation that the client will use this information when processing the response in order to handle each specific type in the response.

Essentially, a GraphQL interface is actually a _combination_ of a Typescript interface and Typescript union. We might represent it something like the following:

**GraphQL**
```
interface Bar {
  x: String!
}

type BarA implements Bar {
  a: String!
  x: String!
}

type BarB implements Bar {
  b: String! 
  x: String!
}

type Foo {
  bar: Bar! 
}
```

**TypeScript**
```
interface Bar {
  x: string;
}

interface BarA extends Bar {
  __typename?: "BarA";
  a: string; 
  x: string;
}

interface BarB implements Bar {
  __typename?: "BarB";
  b: string; 
  x: string;
}

type BarUnion = BarA | BarB;

type Foo {
  bar: BarUnion; 
}
```

**Comment by dotansimha** [comment]
@mjeffryes You are right, and that's the exact output we have today. The generated TS type for GraphQL `interface` doesn't have `__typename`, and the implementing types does have. 

I'm closing this one. It's been around for a long time, and I think we are not going to intentionally change that soon. We are always open for additional configuration flags and customizations, so if someone have a good use-case and want to pick this up and add this - feel free ;)

**Comment by lensbart** [comment]
@dotansimha I’m not sure that @mjeffryes’ example is the output we have today. Taking his example, I get an output that is analogous to

```typescript
type Foo {
  bar: Bar
}
```

instead of

```typescript
type Foo {
  bar: BarUnion
}
```

Because of this, the `__typename` fields which are present on `BarA` and `BarB`, are missing in the value of `bar` inside `Foo`.

Would it be possible to explicitly include all implementations of an interface wherever an interface is used as a value? E.g.,

```typescript
type Foo {
  bar: BarA | BarB
}
```

**Comment by lensbart** [comment]
> (...)
> 
> This seems more correct, because the interface itself is typically missing several fields apart from `__typename`, so without these `Foo` would be incomplete.

Nevermind, as usual the problem was between the computer screen and the chair — I should have used a union instead of an interface in the GraphQL schema, in this use case.

**Comment by mattoni** [comment]
I have a followup question here. 

I'm implementing an error pattern where all possible errors are part of a union type return, i.e. `union Result = FinalizedLogin | ServerError| ValidationError`, Where `ServerError` implements a generic 'Error' interface. One of the main advantages to this pattern is that, in the future, if a new type of error were to be introduced, clients that haven't been updated yet would be able to still handle that case by adding the Error interface fragment as a sort of 'catch all'. With the types being generated here, I don't have access to the Error interface on say, a switch case after using the Apollo hook to make the mutation How would I be able to handle this circumstance?

Thanks!

**Comment by mbrowne** [comment]
I'm surprised that this issue was closed just because there are alternative solutions that work in many cases. Not every schema has queries that return only a subset of all possible types that implement an interface. Sometimes you need to be able to handle _any_ type implementing that interface, and check the `__typename` to determine how to handle it. For example, a generic CMS system that has a generic `Block` interface:

```gql
interface Block {
  blockName: String!
}

type TextBlock implements Block {
  ...
}

type CarouselBlock implements Block {
  ...
}

# etc...
```

**Comment by dotansimha** [comment]
> be

Hi! I usually doing:

```graphql
interface Error {
  message: String!
}

type MyError implements Error {
  message: String!
  extraField: String
}

type MyMutationResult = ValidResult | MyError

```

Then, your consumers can just use `... on Error` as fallback for all error types. And if they need something specific, they can just use another inline fragment for the additional error types.

**Comment by dotansimha** [comment]
> I'm surprised that this issue was closed just because there are alternative solutions that work in many cases. Not every schema has queries that return only a subset of all possible types that implement an interface. Sometimes you need to be able to handle _any_ type implementing that interface, and check the `__typename` to determine how to handle it. For example, a generic CMS system that has a generic `Block` interface:
> 
> ```graphql
> interface Block {
>   blockName: String!
> }
> 
> type TextBlock implements Block {
>   ...
> }
> 
> type CarouselBlock implements Block {
>   ...
> }
> 
> # etc...
> ```

Hi @mbrowne  I'm not sure what's your point here, can you please elaborate? 

Even if you have interface with implementing types and `__typename`, there is not such scenario where GraphQL will return `__typename: Block`. I will always return `__typename: TextBlock` or `__typename: CarouselBlock`.

**Comment by mbrowne** [comment]
@dotansimha 
> Even if you have an interface with implementing types and __typename, there is no such scenario where GraphQL will return __typename: Block

That's true, but my goal is to check `__typename` on an object that could be any Block type. Here's a contrived example:

```ts
switch (block.__typename) {
  case 'TextBlock':
    return <RichText {...block as TextBlock} />
  case 'CarouselBlock':
    return <Carousel {...block as CarouselBlock} />
  ...
}
```

So it would be very helpful if `Block` had something like this:

```
__typename: 'TextBlock' | 'CarouselBlock' | 'ImageBlock' | ...
```

**Comment by dotansimha** [comment]
> @dotansimha
> 
> > Even if you have an interface with implementing types and __typename, there is no such scenario where GraphQL will return __typename: Block
> 
> That's true, but my goal is to check `__typename` on an object that could be any Block type. Here's a contrived example:
> 
> ```ts
> switch (block.__typename) {
>   case 'TextBlock':
>     return <RichText {...block as TextBlock} />
>   case 'CarouselBlock':
>     return <Carousel {...block as CarouselBlock} />
>   ...
> }
> ```
> 
> So it would be very helpful if `Block` had something like this:
> 
> ```
> __typename: 'TextBlock' | 'CarouselBlock' | 'ImageBlock' | ...
> ```

But it does, we generate separate types, but their "merge" at the level of the TS operation type is a TS union type ;)  for example: https://www.typescriptlang.org/play?#code/C4TwDgpgBA8mwEsD2A7AglAvFA3lA+vqJCgIYC2EAXFAORq1QC+A3AFDHRyKoBCWuAkXAQylGrV6NWHEbHjIUAYQF5CnMdTpLp7TvJ4oAIqqEaKW2kd1tZkKAFUUimADM0AGw8DuijAB8DRX5A31QVUIVUI3Y2VwBXFABjQyhgCABnYAAKDKRKYAALBBQAcxonF3cvAEpcNigoDIB3BGAkwtz8iCKS0oA6dRFNOpwGxqgk0gzoeloacYnJ1DyPCH6PJFLsuZr2JamZuikFpcaklaQ1ja2dqT3FyenZnRpGx-PL683t2h0Hg7POjWU5nC4oVbrH47awA5hsJhAA

**Comment by mbrowne** [comment]
Oh...well maybe that's the issue then. So far I'm only using the code generator to generate types from the schema...I haven't tried using it to generate types for operations yet. I'll try that later and report back. Thanks for clarifying!

**Comment by mbrowne** [comment]
I tried generating types for the whole query. It works fine if all you need to do is directly refer to the query result within the same function, but it breaks down when you want to pass the data to a nested React component, or if your interface is being used for the items in a nested list. To continue with the `Block` example, suppose they're being used in this way in the schema:

```gql
type Page {
  content: [Block!]!
  metadata: PageMetadata!
}
```

And that certain Block types can contain nested Blocks:

```gql
type Section implements Block {
  heading: String
  image: Image
  content: [Block!]!
  blockName: String!
}
```

You can easily access the `__typename` of top-level blocks:

```ts
    queryResult.page.content.map(block => {
        switch (block.__typename) {
            ...
        }
    })
```

But not nested blocks:

```ts
// Property '__typename' does not exist on type 'Block'
(queryResult.page.content[0] as Section).content[0].__typename

// Or more realistically, a separate React component:
function Section(section: Section) {
  return (
    <section>
      <header>...</header>
      {section.content.map(block => {
        const blockType = block.__typename
        ...
      }}
    </section>
  )
}
```

Or even just a helper function (this wouldn't work even if passed a top-level block in `page.content`):

```ts
function renderBlock(block: Block) {
  const blockType = block.__typename
  ...
}
```

For any cases like this, I think it would still be very helpful to have `__typename` defined in the interface types.

**Comment by dotansimha** [comment]
> ```ts
> Block
> ```

You shouldn't use `Block` directly since it generated as base type. The actual type is based on selection set. 
If you wish to have a sub-type for that selection, use fragments and then you'll get a `BlockFieldsFragment` with `__typename` and this will represent your actual client-side types.

**Comment by mbrowne** [comment]
Ok I had to rearrange my fragments a bit, but that should work - thank you. It still feels a bit like a workaround, but I think I see what you're saying—if the query doesn't check for a particular type that implements the interface, then obviously you're never going to receive an object of that type from that query. But I wonder if this level of strict type checking and needing to reference fragments might be overkill in some cases.

**Comment by dotansimha** [comment]
> Ok I had to rearrange my fragments a bit, but that should work - thank you. It still feels a bit like a workaround, but I think I see what you're saying—if the query doesn't check for a particular type that implements the interface, then obviously you're never going to receive an object of that type from that query (or at least, not with any fields unique to that type). But I wonder if this level of strict type checking and needing to reference fragments might be overkill in some cases.

Exactly, the client will never know about the `interface` so you need to deal with the types generated based on your query/selection-set. 
Fragments are useful for other use-cases and make it easier to create "building blocks" that create complex queries. We translate these into types because it's named, and it's keeping the usage simple.

**Comment by mattoni** [comment]
> > be
> 
> Hi! I usually doing:
> 
> ```graphql
> interface Error {
>   message: String!
> }
> 
> type MyError implements Error {
>   message: String!
>   extraField: String
> }
> 
> type MyMutationResult = ValidResult | MyError
> ```
> 
> Then, your consumers can just use `... on Error` as fallback for all error types. And if they need something specific, they can just use another inline fragment for the additional error types.

I think this changes the query quite a bit and isn't what I'm trying to accomplish. If I have `FinalizedLogin | ServerError| ValidationError`, I want to distinguish between a ServerError and a ValidationError, on a type level. Now say I add `Unauthenticated` or something. My old clients could crash, despite the query working by doing an `... on ErrorInterface`. I want to have the same thing, say a switch case where I can do `case ErrorInterface:` to handle all future implementations of errors that may arise my client isn't equipped to handle.
