### ISSUE TITLE
Enums that have values different from keys are not properly generated

### ISSUE THREAD

**Issue by reubenab** [dotansimha/graphql-code-generator#3444]
**Describe the bug**
 
Enums that are defined in a resolver in order to map values that are different to the key (as described [here](https://www.apollographql.com/docs/apollo-server/schema/scalars-enums/#internal-values) in the apollo docs) are not added to the `type Resolvers` in the code-generated `schema-types`, throwing a typescript error in the resolver (even though the server will run fine and execute as expected).

**To Reproduce**
1) Define an enum in the schema typeDefs in a `schema.ts` file
```
enum StatusCode = {
  CURRENT
  LATE
}
```
2) Use that enum in another type
```
type Status {
  name: String
  statusCode: StatusCode!
}

extend type Query {
  status: Status
}
```
3) Define a mapping for that enum in the associated resolver because the data source in the backend has a different value (e.g. lowercase instead of uppercase)
```
resolvers: {
  StatusCodes: {
    CURRENT: 'current',
    LATE: 'late',
  }
}
```
4) Notice that the following typescript error shows up:
```
Type 'StatusCode' is not assignable to type 'Resolvers<any>'.
 Object literal may only specify known properties, and 'StatusCodes' does not exist in type 'Resolvers<any>'.ts(2322)
globals.ts(7, 3): The expected type comes from property 'resolvers' which is declared here on type 'Schema'
```

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
```

**Expected behavior**

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**

**Comment by ardatan** [comment]
@reubenab You have two options to have correct values for enums.
1. If you want to give SDL/typeDefs as your schema pointer in codegen.yml, you need to define your own `enumValues` .
https://graphql-code-generator.com/docs/plugins/typescript#enumvalues-enumvaluesmap
2. You need to give exact schema object using URL or executable `GraphQLSchema` that is generated by `makeExecutableSchema` or something else that has correct enum values as in you defined in resolvers.

Otherwise, GraphQL Codegen is unable to get your enum values only from typeDefs.

**Comment by nwalters512** [comment]
Hey @ardatan, thanks for the quick reply! That's a related issue, but isn't the particular problem we're facing. We're trying to take advantage of Apollo's "Internal values" feature: https://www.apollographql.com/docs/graphql-tools/scalars/#internal-values. This involves defining a resolver for the enum's type, as shown in the Apollo docs. However, because the `typescript-resolvers` plugin doesn't generate those types, defining such a resolver becomes a type error. 

Here's a codesandbox reproduction of this: https://codesandbox.io/s/cranky-black-dv4oz. If you open `schema.ts`, you'll see that the resolver for `UserType` is flagged as a type error.

**Comment by reubenab** [comment]
Hi @ardatan! Just wondering if you have any more insight into this issue. Thanks!

**Comment by anilanar** [comment]
@nwalters512 Internal values for enums isn't a feature of apollo, it's a feature of `graphql`.
E.g.

```
import { makeExecutableSchema } from 'graphql-tools';

makeExecutableSchema({
  typeDefs: gql`
     enum Animal {
       Cat
       Dog
     }
  `,
  resolvers: {
    Animal: {
      Cat: 'cat',
      Dog: 'dog'
    }
  }
})
```

The problem is, `Resolvers` type that `typescript-resolvers` generates doesn't have fields for enum types. E.g. it should look something like:

```
export type Resolvers<ContextType> = {
   Query?: ...,
   Mutation?: ...,
   ...,
   Animal?: EnumResolverObject<...>,
}
```

And then, we can pass the enum type generated by code-gen or custom `enumValues`:

```
const resolvers: Resolvers = {
  ...,
  Animal: AnimalEnum,
}
```

Does that make sense @ardatan ?

**Comment by dotansimha** [comment]
I think you are right @anilanar . It seems like we should add a signature for enum resolvers. PRs are welcome :D

**Comment by gsaini** [comment]
1+

**Comment by dotansimha** [comment]
This was added a long time ago :) see: https://github.com/dotansimha/graphql-code-generator/issues/3985
