### ISSUE TITLE
TypeScript operations queries doesn't mark fields optional

### ISSUE THREAD

**Issue by stephenh** [dotansimha/graphql-code-generator#3463]
Given a schema like:

```graphql
type Child {
  parent: Parent
}
```

The default `typescript-operations` output for `Child` is:

```typescript
export type Child = {
  parent?: Maybe<Parent>;
}
```

Which is fine, however, if I write a query:

```graphql
 query Foo {
  child(...) { parent { name } }
}
```

The generated type is:

```typescript
export type FooQuery = {
  { __typename?: 'Query' } &
  { child: (
    { __typename?: "Child" } &
    & parent: (
      { __typename? "Parent" } &
      Pick<Parent, "name">
    )
  )}
}
```

(I'm butchering the nested types a bit.)

Note that `parent` here in the query is `parent` and not `parent?`.

This inconsistency between the top-level type and the query type means I can't do:

```typescript
const child: Child = newFactoryMethodForChild();
assertTestWithFooQueryResult({ query: { child }));
```

(Again being somewhat loose with syntax.)

Because there is a type error that `Child`'s `parent` is optional (`Parent | null | undefined`) but the query's munged-together anonymous type wants `parent` to be `Parent | null`.

This is internally inconsistent.

Note that if I use `avoidOptionals: true`, it turns the top-level `Child` into `parent: Maybe<Parent>` and so now my "factory method that makes `Child`s" and "unit test that handles foo query results" structurally matches and compiles fine.

However there are other downsides to `avoidOptionals` (specifically that it should never apply to input types), so it'd be nice to keep `avoidOptionals` off (on the client-side types; on the server-side types I think avoidOptionals is generally best-practice fwiw).

**Comment by dotansimha** [comment]
@stephenh While dealing with the schema types - we can allow optionals and allow `undefined` because the GraphQL engine knows how to handle that.
But, if you are writing a query and ask for specific fields, the GraphQL engine will always return the field for you, and if an nullable field, it means that it could be either a value, or `null` - but the field will always be there. 
You should not use `Child` (or any base type generated by `typescript` plugin) directly as a consumer of queries - because it represents the complete type and not the selection set your query is asking for.

You can customize the output with `avoidOptionals` or `maybeValue` and change the output according to your needs.
