### ISSUE TITLE
Typescript development workflow?

### ISSUE THREAD

**Issue by sarink** [dotansimha/graphql-code-generator#3587]
This isn't really a bug per se, but I'm trying to understand how one can use this project. Here is a catch-22 scenario I am confronted with almost daily, and I'm not sure how to work around it:

Let's suppose you need to modify the return type of a resolver:
1. Update `resolver.ts`
2. Now, typescript is complaining, because what your new resolver is returning does not match the return type of that resolver in the codegen'ed types file. So, you update your graphql `typedefs.ts`, and re-run `codegen`
3. Gotcha! `codegen` doesn't care about your new `typedefs` yet, first it will try to download the latest schema, but error, because typescript is not compiling, so the server is not running... ♻️ 

The only solution I can find is to manually edit the return type of the resolver in codegen's output file, so that the typescript will compile and the server will run again. Obviously, this defeats the entire purpose of using this lib at all.

Can someone please explain what I'm missing? Can `codegen` run off of my graphql `typedefs.ts` file instead of the schema? Or is there some other solution?

Thanks!

**Comment by dotansimha** [comment]
@sarink can you please share a repository? It will help to see how you constructed the code and schema files.

The workflow we are using, is to do schema-first:
1. Define you schema in `.graphql` files.
2. Run codegen and generate resolvers signature (to `resolvers.types.ts`) 
3. Implement resolvers in a new file (`resolvers.ts`) using the `Resolvers` type signature from the generated file. 
4. Now, if you wish to change a return type or something else, do it first in your schema file - if your codegen runs in watch mode, it will automatically update the resolvers signature file, and it will cause your code to be type checked again, and update your resolvers implementation as needed.

If you wish to put your resolvers implementation and schema definition in the same file, you can still do it, I think you just need to specify `noRequire: true` because otherwise the codegen will have issues to require the file (because if will cause compilation errors from the changes).

Do it answer you question? Did I miss anything?

**Comment by sarink** [comment]
The missing piece here was that you can tell codegen to generate a schema from your source files rather than from a running service, ie `schema: ./src/**/*TypeDefs.ts`

Thanks!

**Comment by dotansimha** [comment]
@sarink You can use endpoint, code file, graphql file and some more. See the list of loaders here: https://github.com/dotansimha/graphql-code-generator/blob/d3438740d96c8c716c3af65b73f2b7f7a9e70c3d/packages/graphql-codegen-cli/src/load.ts#L16
