### ISSUE TITLE
Are dotnet plugins ( F# or C#) planned?

### ISSUE THREAD

**Issue by JanDonnermayer** [dotansimha/graphql-code-generator#3622]
I would like to use the generator to create F#  types.
Is something like this on the roadmap?

At the moment, F# type-providers exist for GraphQL. However, they cannot create reusable class-libraries.

**Comment by dotansimha** [comment]
Hi @JanDonnermayer ! 
We don't have C# or F# plugins that are maintained by use at the moment. 

The following might help you?

- https://github.com/netspective/graphql-codegen-csharp 
- https://github.com/agoda-com/graphql-codegen-csharp 

The reason we don't have our own plugins for .NET moment is because we are not using it regularly in our projects, so it's hard for us to generate the optimal code. 
PRs are always welcome, and if wish to write your own plugin, we're here to help ;)

**Comment by JanDonnermayer** [comment]
Hi @dotansimha,

thanks for your reply! The links are super helpful!
I will evaluate both of them, as well as contributing to this repo.

**Comment by dotansimha** [comment]
We can close this one, we have 2 new plugins for C#.

**Comment by JanDonnermayer** [comment]
Awesome, I will definitely use them!
