### ISSUE TITLE
Code generation for inline queries

### ISSUE THREAD

**Issue by cometkim** [dotansimha/graphql-code-generator#3997]
**Describe the solution you'd like**

In order to use codegen-based tools, I need to write queries far from the code. But I wanna write queries to be inlined inside the code AND the type declarations generated are automatically bound.

Tools like graphql-let are useful, but TypeScript's inference feature makes things even smarter.

I know how to do this, but I am not sure where is the right place to.

**Describe alternatives you've considered**

example:

```ts
// $ExpectType UserData
useQuery(`
  query User($id: String!) {
    user(id: $id) {
      id
      username
      fullName
      email
    }
  }
`);

// $ExpectType PostData
useQuery(`
  query Post($id: String!) {
    post(id: $id) {
      id
      category
      title
      description
    }
  }
`)

// genarated code looks like this:
type QueryResult<Query extends string> = (
  Query extends UserQuery ? UserQueryResult :
  Query extends PostQuery ? PostQueryResult :
  any
);

// client's useQuery should be overwriten
function useQuery<Query extends string>(query: Query): QueryResult<Query>;

// extracted from useQuery(`...`)
type UserQuery = `
  query User($id: String!) {
    user(id: $id) {
      id
      username
      fullName
      email
    }
  }
`;

type UserQueryResult = {
  _brand: "User",
};

type PostQuery = `
  query Post($id: String!) {
    post(id: $id) {
      id
      category
      title
      description
    }
  }
`;

type PostQueryResult = {
  _brand: "PostData",
};
```

This code can be easily generated through codegen plugin, but finally, the client's useQuery type declaration must be overwritten.

**Additional context**

**Comment by threehams** [comment]
I'm in the middle of figuring this out, with a WIP branch in the middle of a personal project: https://github.com/primitiveconcept/ludumdare46/compare/codegen?expand=1

The main problem I'm having is that tools other than `graphql-code-generator` only support this:
```
gql``
```
not one of these:
```
gql<"Type">``
gql(``)
```

I haven't found a way to get TypeScript to extract the literal value from a tagged template literal; the input has to be `TemplateStringsArray`, so the extracted generic from it ends up being `string`. That leaves: make `gql` a function, or give `gql` a type param. Neither one of these is really supported by any other tools (in editor or otherwise).

**Comment by threehams** [comment]
Your more immediate question:
> I know how to do this, but I am not sure where is the right place to.

There's a "hooks" config property that lets you run anything after codegen completes. I'm using that here:
https://github.com/primitiveconcept/ludumdare46/compare/codegen?expand=1#diff-d6ac51fc77e5e52e810e1ab39e41c764R6-R10
to run a Babel plugin here:
https://github.com/primitiveconcept/ludumdare46/compare/codegen?expand=1#diff-69dd8ef9ba9d159595a7606869f7b8ecR1-R21
which adds an exported type containing all operations by name.
For your approach, `typescript-react-apollo` will generate code like this:
```
export const UserFieldsFragmentDoc = gql`
fragment UserFields on User {
  id
  username
  role
}
```
You can use Babel traverse to find those and build up your type object, or convert them to what you need.

Otherwise, you're in custom plugin land. Good luck.

**Comment by dotansimha** [comment]
Our tool for extracting queries is `graphql-tag-pluck` (https://github.com/ardatan/graphql-toolkit/tree/master/packages/graphql-tag-pluck). I looks for `gql` template usages and tries to extract strings from it. 

If you wish to write it inline, without `gql`, you can use the magic GraphQL comment (it also detected by most IDEs), like that:

```
useQuery(/* GraphQL */`
  query Post($id: String!) {
    post(id: $id) {
      id
      category
      title
      description
    }
  }
`)
```

This way, `graphql-tag-pluck` will be able to find it as well.
