### ISSUE TITLE
make near-operation-file preset the default

### ISSUE THREAD

**Issue by capaj** [dotansimha/graphql-code-generator#4370]
I am writing react apps and I kinda dislike the fact that my whole schema with all my queries/mutations is always outputted into a single file.
Wouldn't it be nicer if  graphql-code-generator could generate a file next to the source `gql` file where my query/mutation is?
This way importing it would be easier in my components, because I always have it just one dot away when traversing filesystem.
Also on huge project like the one we have at @LeapLabs TS compiler would be much faster to index that new type/hook/thing because it's much faster at parsing and adding one small file vs parsing and indexing a huge file.

I know this would be a huge breaking change, but maybe for next major?

**Comment by ardatan** [comment]
Is that what you're looking for?
https://graphql-code-generator.com/docs/presets/near-operation-file

**Comment by capaj** [comment]
thanks that looks exactly like what I am looking for

**Comment by capaj** [comment]
I have a question-Why is this not the default mode?
Is there an objective quality of the current mode that I am missing?
Seems like more general preset that suits better for both small and big projects is near-operation-file. Why is it not the default?

**Comment by dotansimha** [comment]
Hi @capaj 
We prefer to maintain single-type output, because it's easier and we don't need to deal with imports. 
In most cases, anything that can be done with multiple files - can be done with a single file - especially when it's related to TypeScript types. Having multiple generated files means that you need to maintain and track all those somehow.

**Comment by capaj** [comment]
Thanks for your reply. Understandable. Would be nice document the drawbacks of a single file aproach in the docs somewhere. We're getting to a point where typescript parser is getting a bit slow for us to work with the single file of 50k LOC and it will be a bit of work to swap it to `near-operation-file`. It would really have been nice to have a friendly warning when we started with graphql-code-generator.

**Comment by dotansimha** [comment]
@capaj I'm not sure that `tserver` performance should be affected by a file with a lot of types. Eventually, it has the same `ts.Program` with the same amount of TypeScript types. 
Maybe this could be fixed with a different solution? Can you please share more details about the experience of working with a single file and how it's effects your workflow? 
From our experience, working with multiple files usually comes with the overhead of maintaining tons of files, and it bloats the repo and doesn't improve IDE / TS performance, so it could be really interesting to hear your thoughts on that. Thanks!
