### ISSUE TITLE
Align TypeScript Urql plugin with React Apollo

### ISSUE THREAD

**Issue by Pytal** [dotansimha/graphql-code-generator#4494]
In [TypeScript React Apollo v2.0](https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Ftypescript-react-apollo%402.0.0) React Hooks are generated by default and Components are not.

Hooks should be generated by default with TypeScript Urql as well to maintain consistency.

**Comment by dotansimha** [comment]
Thanks @Pytal , but can you please explain why it's needed?
In Apollo-Client v3, the Component and HOC approaches are deprecated, while in Urql it isn't. That's the reason we changed it and published major version for it. 
I think we can enable `withHooks` by default, but maybe we can keep the rest to avoid the breaking change, because it's not needed.

**Comment by dotansimha** [comment]
I was thinking some more on this, and decided to align to the recomended form of using `urql`. In the upcoming major version of this plugin, it will use `withHooks: true, withComponent: false` by default.
Thanks @Pytal

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript-urql@2.0.0`.

**Comment by Pytal** [comment]
Thanks @dotansimha!

I was questioning my initial decision as well after you mentioned that it would be a breaking change.

Although since the React ecosystem is moving away from both Component and HOC libraries and more towards Hooks I do believe this is a modernization that is warranted. I think the Apollo team were thinking along these lines as well.
