### ISSUE TITLE
When using apollo generator, the gql fragment is recreated in the generated code causing a warning

### ISSUE THREAD

**Issue by vjpr** [dotansimha/graphql-code-generator#4795]
**Describe the bug**

When using apollo generator, the gql fragment is recreated in the generated code causing a warning because the fragment is being created with `gql` tag in two places.

```
 Warning: fragment with name CompanyFragment already exists.
      graphql-tag enforces all fragment names across your application to be unique; read more about
```

**To Reproduce**

```
const companyFragment = gql`
  fragment CompanyFragment on Company {
    name
  }
}

const QUERY_COMPANIES = gql`
  query GetCompanies($where: JSONObject) {
    companies(where: $where) {
      name
      ...CompanyFragment
    }
  }
  ${companyFragment}
` 
```

Use `typescript-react-apollo`

**Additional context**

https://github.com/apollographql/apollo-client/issues/940

Not sure if this is actually a problem though...

**Comment by dotansimha** [comment]
Hi @vjpr ! 
You can either play with `documentMode` configuration to change the way we generate the operations. You can even pre-compile it into `DocumentNode` and avoid doing that in runtime. 
Also, you can just use the compiled / generated documents instead of the original ones, and it won't trigger this warning.

You can also disable this warning in `graphql-tag`: https://github.com/apollographql/graphql-tag#warnings
