### ISSUE TITLE
Branded Scalar types

### ISSUE THREAD

**Issue by marisbest2** [dotansimha/graphql-code-generator#4912]
We recently ran into a bug where we had two different scalar types `DogId: string` and `PersonId: string`. In one place in the codebase we accidentally passed `dog.id` instead of `dog.owner_id`. It'd have been great if this had generated a type error.

A nice solution would allow us to have tagged/branded types (see e.g. https://medium.com/better-programming/nominal-typescript-eee36e9432d2).

This would transform 
```graphql
scalar DogId
scalar PersonId

type Dog {
   id: DogId!
   owner_id: PersonId!
}

type Person {
   id: PersonId!
}
```

into 

```typescript
type DogId = any & { private __type: 'DogId' }
type PersonId = any & { private __type: 'PersonId' }
type Person = { id: PersonId }
type Dog = { id: DogId, owner_id: PersonId }
```

A tentative (not scalable solution) is for us to configure these types in the custom scalar map, but we'd need to do that for every type.

A proposed config would look like

```yml
useBrandedScalarTypes: bool
```

I'm new to this codebase so I'm not sure what the lift / process for accepting this FR would be.

**Comment by dotansimha** [comment]
Hi @marisbest2 
This seems like a very specific use-case, and I don't think we can address that.
You can use `scalars` configuration to set the scalars types to anything. You can even use external files/identifiers if you need to.

**Comment by maclockard** [comment]
@dotansimha I'm not sure I agree that this is a very specific use case. I'm currently going through the process of adding type brands to our ids in order to prevent 'wrong id type' bugs. graphql-code-generator does allows this as you point out, but it would be nice to have a config option to make this common pattern less manually intensive, particularly if there are many different possible types.

For more justification why this is usually a good idea, take this function for example:
```ts
function getDog(id: string): Dog {
...
}
```
It would allow both of these calls at compile time:
```ts
getDog(dog.id); // okay!
getDog(person.id); // runtime error :(
```
However, with type branded ids you would instead have this function signature:
```ts
function getDog(id: DogId): Dog {
...
}

getDog(dog.id); // okay!
getDog(person.id); // compile error :)
```

In this case, its pretty trivial to see the error of passing a person id to this function, but in a non trivial code base where ids are passed around, it gets a bit easier to fat finger such an error.

**Comment by maclockard** [comment]
Just found https://github.com/dotansimha/graphql-code-generator/issues/3049 and I think I might prefer that as a solution over this, to at least give more granular control

**Comment by marisbest2** [comment]
It looks like #3049 also suggests using autogenerated branded ids.

> This, or some kind of inflector that could make branded ids based on a pattern would be INCREDIBLE for this workflow.

Our pipeline has our schema generated from Python/Graphene -> schema.graphql -> typescript. A solution that requires maintaining a separate .d.ts (or any other file) is the same lift as a solution that requires us maintaining a scalar map in config.
