### ISSUE TITLE
[TypeScript React-Query] export fetcher from each query

### ISSUE THREAD

**Issue by vitorcamachoo** [dotansimha/graphql-code-generator#5526]
**Is your feature request related to a problem? Please describe.**
If we want to use the feature from Next.js, Incremental Static Regeneration, we need the fetcher itself to be executed on the static method `getStaticProps`. If the user uses `Typescript React-Query` to generate the queries, he will need the fetcher exported to be used separately.
At the moment I can't get `Incremental Static Regeneration` on my project using generators.

**Describe the solution you'd like**

We can do something related with the option to export unique key for the query and aggregate the fetcher like:
inside query variable, aggregate fetcher method:
useQuery
  -  getKey (already present)
  -  fetcher
  

```tsx
import { useQuery } from './gen'

export function Index(props) {
  const { data } = useQuery()

  return <Component />
}

export async function getStaticProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery(userQuery.getKey(), () => userQuery.fetcher())

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

```
**Describe alternatives you've considered**

**Additional context**

**Comment by dotansimha** [comment]
I might be missing something here, but the `fetcher` is generated before each hook, and generally available for you to use. I think you can just use the fetcher as-is? Or you wish it to be wrapped somehow?
Maybe you can share an example of how `userQuery.fetcher` should be generated?

**Comment by vitorcamachoo** [comment]
Hi,
This is is a good example made for swr (https://www.npmjs.com/package/graphql-codegen-plugin-typescript-swr). Basically, this should generate a fetcher and a hook for the same fetch method so we can use the fetch for getInitialProps (nextjs) and the hooks for the component itself.

**Comment by iksent** [comment]
I want to add a few words from my side:
1) It would be great to use the request functions that are used for hooks, because it is not always possible to use hooks (for example, on the server side)
2) The second problem is that now even the main fetcher is not exported and you have to write your own

```
export const useGetArticlesQuery = <TData = GetArticlesQuery, TError = unknown>(
  variables?: GetArticlesQueryVariables,
  options?: UseQueryOptions<GetArticlesQuery, TError, TData>,
) =>
  useQuery<GetArticlesQuery, TError, TData>(
    ['getArticles', variables],
    fetcher<GetArticlesQuery, GetArticlesQueryVariables>(GetArticlesDocument, variables),
    options,
  )
```

Where `fetcher` is (with no export at all...):
```
function fetcher<TData, TVariables>(query: string, variables?: TVariables) {
  return async (): Promise<TData> => {
    const res = await fetch(`${process.env.API_BASE_URL || ''}/graphql` as string, {
...
```

So for Next.js I use:

```
static async getInitialProps(appContext: AppContext) {
  const _queryClient = new QueryClient()
  await _queryClient.prefetchQuery(
    'getStatistics',
    fetcher<GetStatisticsQuery, GetStatisticsQueryVariables>(GetStatisticsDocument, {}),
  )
  ...
}
```

But want something like this:
```
static async getInitialProps(appContext: AppContext) {
  const _queryClient = new QueryClient()
  await _queryClient.prefetchQuery(
    useGetStatisticsQuery.key, // Defined and exported key
    fetchArticles, // Defined and exported fetcher
  )
  ...
}
```

**Comment by Xetera** [comment]
You can mitigate the issue a tiny bit by manually exporting the unexported `fetcher` with
```yaml
plugins:
  - add:
      placement: append
      content: "export { fetcher }"
```
but even then there's no type safety since the variables are not bound to the query being made.

The state of graphql data fetching libraries on nextjs is quite abysmal right now. next-apollo has big caveats with `getServerSideProps` (and more) that make it unusable, SWR doesn't support the hydration pattern and react-query has codegen issues. If a maintainer would be kind enough to hold the ropes with examples that might be relevant/useful in getting this feature implemented, I would be interested in giving it a shot because right now working with data fetching in nextjs is a terrible dev experience.

**Comment by luisrudge** [comment]
@Xetera lol. I was literally thinking the same thing! Just putting my feet on the water on this subject and everything is all over the place. I'm totally lost with the codegen part, since nothing kinda fits the nextjs solution. TBH, nextjs data fetching strategy is also all over the place.. I think react-query's strategy is the best one and super easy to implement:

```
export async function getServerSideProps() {
   const posts = await getPosts()
   return { props: { posts } }
 }
 
 function Posts(props) {
   const { data } = useQuery('posts', getPosts, { initialData: props.posts })
 
   // ...
 }
```

The issue now is with codegen, since I don't want to keep creating functions for everything, since I can codegen them hehe.

**Comment by paolotiu** [comment]
Attempted in #6365

**Comment by dotansimha** [comment]
Available in `@graphql-codegen/typescript-react-query@2.0.0`
