### ISSUE TITLE
Why isn't string mentioned as an option for documentMode?

### ISSUE THREAD

**Issue by AradAral** [dotansimha/graphql-code-generator#5615]
The `documentMode` configuration option apparently has a possible value other than what's listed in the docs:

![image](https://user-images.githubusercontent.com/26527405/109228150-a92df480-77d6-11eb-8b13-545e9cd88469.png)

And it's `string`. I found out that such an option exists after looking at the source code ([here](https://github.com/prisma-labs/graphql-request/blob/a8d99f5cdbe57786ecb8d99c88175599608d2fc6/src/index.ts#L207-L211) to be specific). This is in fact a very useful option in certain situations, and I actually created an issue asking for it to be implemented (#5613) which I immediately closed after realizing that it already exists.

But why isn't it listed in the possible values for the `documentMode` configuration option? This caused me a headache!

By the way, why does it say that the type of the `documentMode` configuration option is `DocumentNode`?! (You can see that in the above picture). It should be `string`, because of course we're talking about the configuration option values here.

**Comment by ardatan** [comment]
The documentMode configuration option apparently has a possible value other than what's listed in the docs:
This comes from here https://github.com/dotansimha/graphql-code-generator/blob/4ea2ccd0f7dcb9486145bd7abec6804f6d756f26/packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts#L114
I think most of the other plugins don't support `string` inputs like `graphql-request` that's why we might ignore that option on purpose. @dotansimha correct me if I'm wrong?

> By the way, why does it say that the type of the `documentMode` configuration option is `DocumentNode`?! (You can see that in the above picture). It should be `string`, because of course we're talking about the configuration option values here. 

No it says `DocumentMode` not `DocumentNode` :) 
https://github.com/dotansimha/graphql-code-generator/blob/4ea2ccd0f7dcb9486145bd7abec6804f6d756f26/packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts#L25

**Comment by AradAral** [comment]
> No it says DocumentMode not DocumentNode :)

Oops yeah sorry I misread that :D

> I think most of the other plugins don't support string inputs like graphql-request that's why we might ignore that option on purpose. @dotansimha correct me if I'm wrong?

Ok but if that's the case then can't we mention it only for plugins that **do** support it?

**Comment by dotansimha** [comment]
You are both right :) This should definitely be mentioned. I updated the docs in: https://github.com/dotansimha/graphql-code-generator/commit/0bdd45534e3702181407ac399425fcbe90c04312 
Will be available soon, with the next deployment :)

**Comment by AradAral** [comment]
@dotansimha Thank you so much!
