### ISSUE TITLE
preset graphql-modules does not create interface resolvers for modules

### ISSUE THREAD

**Issue by jjangga0214** [dotansimha/graphql-code-generator#5800]
**Describe the bug**
 
When using preset `graphql-modules` with plugin `typescript-resolvers`, types for interface resolvers are not created for module.

**To Reproduce**

codesandbox: https://codesandbox.io/s/trusting-roentgen-k9fv6?file=/module/node/generated.ts:494-503

It should be 

```typescript 
  export interface Resolvers {
    Query?: QueryResolvers;
    Node?: NodeResolvers;
  };
```

, but actually 

```typescript 
  export interface Resolvers {
    Query?: QueryResolvers;
  };
```

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

**Comment by dotansimha** [comment]
Hi @jjangga0214 , sorry for the late reply. This was already fixed and available in the latest version of the plugin. It's generated as a standalone type and not as part of `AccountResolvers` because GraphQL spec doesn't support resolvers for interfaces, only for types. And with `graphql-modules` we recommend to use `isTypeOf` instead of `resolveType` since it makes your resolvers more flexible, and you don't need to introduce resolvers for interfaces.
