### ISSUE TITLE
Typechecking fragments is very slow

### ISSUE THREAD

**Issue by markjm** [dotansimha/graphql-code-generator#5991]
Hi @dotansimha - long time no chat.

I have been investigating our typescript typechecking performance recently and have narrowed down a huge time-sink to be these fragments, as the the complex type comparison with the big nested object takes a lot of time.
![image](https://user-images.githubusercontent.com/16494982/118063398-ddcd3900-b34d-11eb-83a1-f5d90786e322.png)

Attaching a coarse pic of a TS trace of ours (feel free to ping me for greater breakdown of the trace).
![image](https://user-images.githubusercontent.com/16494982/118063499-0fde9b00-b34e-11eb-9b0e-1443323992f7.png)
All the circled time is spent typechecking these objects.

**Describe the solution you'd like**
I am attaching a PR with a pretty simple fix. Basically, since we autogenerate these types, we really dont need to typechecking them again (since we are confident in this toolchain :)). Instead, we will just cast these objects to the right type so places relying on them still see them correctly, but we dont pay the cost of confirming them.

Please let me know if you are ok with this approach. If so, I will fix up all the failing tests (since changing output, will need to change the goldens to match).

**Describe alternatives you've considered**
Alternatively, for the same reasons described above, we could really just straight emit the .d.ts and .js files mimicing what TSC will do anyway. Since that seems like a larger change with more consequences than I am aware, i think this approach should be considered for the future but is not implemented now.

**Comment by kenotron** [comment]
Emitting to d.ts is supported already via the tool but not sure about the pure .js portion of the doc nodes.

**Comment by m-rutter** [comment]
> Emitting to d.ts is supported already via the tool but not sure about the pure .js portion of the doc nodes. Hinting TS to make it go faster is 💯 though!

Out of curosity, what configuration emits a delcaration file?

**Comment by dotansimha** [comment]
Thank you @markjm ! This is a great catch. I agree that we don't have to do type-checking on these, and the solution you suggested in https://github.com/dotansimha/graphql-code-generator/pull/5992 seems to be a nice way to go. Can you please take a look at the failing tests? I assume it's just a matter of fixing the snapshots / hardcoded strings in tests, right? 


> > Emitting to d.ts is supported already via the tool but not sure about the pure .js portion of the doc nodes. Hinting TS to make it go faster is 💯 though!
> 
> Out of curosity, what configuration emits a delcaration file? Does it also emit a js file?


When we initially started with codegen, we wanted to use a single `d.ts` for all types but it wasn't possible because TS doesn't allow to do module augmentation for local files, and we didn't have support for generating multiple files (we do have now, with `preset` feature). 


With the default output of codegen, you'll see some TS `enum`s, which are not valid in a `.d.ts` file. You can tweak that with `enumAsConsts` and some other config flags that will make sure to emit only code that is valid in a `d.ts` file. But we don't generate the `.js` file at the moment, since it wasn't a requirement so far. We can definitely consider that (feel free to open a separate issue/PR for that). My only concern is compatibility with other plugins because this will probably break some things we generate today, like hooks.

**Comment by m-rutter** [comment]
> Thank you @markjm ! This is a great catch. I agree that we don't have to do type-checking on these, and the solution you suggested in #5992 seems to be a nice way to go. Can you please take a look at the failing tests? I assume it's just a matter of fixing the snapshots / hardcoded strings in tests, right?
> 
> > > Emitting to d.ts is supported already via the tool but not sure about the pure .js portion of the doc nodes. Hinting TS to make it go faster is 💯 though!
> > 
> > 
> > Out of curosity, what configuration emits a delcaration file? Does it also emit a js file?
> 
> When we initially started with codegen, we wanted to use a single `d.ts` for all types but it wasn't possible because TS doesn't allow to do module augmentation for local files, and we didn't have support for generating multiple files (we do have now, with `preset` feature).
> 
> With the default output of codegen, you'll see some TS `enum`s, which are not valid in a `.d.ts` file. You can tweak that with `enumAsConsts` and some other config flags that will make sure to emit only code that is valid in a `d.ts` file. But we don't generate the `.js` file at the moment, since it wasn't a requirement so far. We can definitely consider that (feel free to open a separate issue/PR for that). My only concern is compatibility with other plugins because this will probably break some things we generate today, like hooks.

Not really a feature request. I'm just concious, like the OP, about compile times related to codegen emitted from the tool. We have some quite large union types and fragments of those union types that from what I can tell from the tsc profiling tools take up signficant chunks of both time and memory. We quite regularly hit some heap allocation errors if say we have both codegen and tsc running in watch modes. IDE feedback in files that are importing from these large codegen files is quite slow. The near operations preset seems has helped a lot in this regard with IDE responsiveness, but not so much with incremental compilation using `tsc` on the command line.

If this PR/feature request addresses some of that by getting `tsc` to skip some unnecessary type checks of object literals, then I wouldn't need a d.ts file.

**Comment by markjm** [comment]
Closing as linked PR is completed
