### ISSUE TITLE
urql-introspection doesn't respect "include" options

### ISSUE THREAD

**Issue by aldrio** [dotansimha/graphql-code-generator#6052]
**Describe the bug**

I'm unable to expose the scalars in my schema output from `urql-introspection` despite setting `includeScalars: true` . I just get an Any. It seems like none of the `include` options that should be passed to urql work

I think it's because this duplicated call to `minifyIntrospectionQuery`. only the inner one is passed the options
https://github.com/dotansimha/graphql-code-generator/blob/d3fba79006f7babcde39c78df98f7ccdc86c1367/packages/plugins/other/urql-introspection/src/index.ts#L123-L130

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

https://codesandbox.io/s/nifty-water-i9k7y?file=/types.ts

1. My GraphQL schema:

```graphql
scalar Wower

type Query {
    cool: Wower
}
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - urql-introspection
config:
  includeScalars: true

```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

The scalar to be in the output

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by Urigo** [comment]
Hi @aldrio and thank you for the report!

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It seems already got into `stage 1` thanks to your reproduction! Thank you for that!

Now in order to advance to `stage 2` we'll need a failing test, would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/urql-introspection@1.3.1`
