### ISSUE TITLE
Codegen doesn't work with Apollo client 3.4 and Typescript

### ISSUE THREAD

**Issue by maciejregula** [dotansimha/graphql-code-generator#6084]
**Describe the bug**
Codegen doesn't work with apollo client 3.4 and Typescript.
**Generic type 'BaseMutationOptions ' requires 4 type argument(s).**

**To Reproduce**
1. Install apollo client 3.4, for example: 3.4.0-rc.3
2. Generate graphql types `graphql-codegen`
3. My `codegen.js` config file:

```js
const schema = process.env.CI
  ? "graphql.schema.json"
  : "https://orbit.vu/graphql";

module.exports = {
  schema: [schema],
  documents: [
    "./src/graphql/queries/*.tsx",
    "./src/queries/*.ts",
    "./src/graphql/mutations/*.tsx",
    "./src/mutations/*.ts",
  ],
  overwrite: true,
  generates: {
    "./src/generated/graphql.tsx": {
      plugins: [
        "fragment-matcher",
        "typescript",
        "typescript-operations",
        "typescript-react-apollo",
      ],
      config: {
        skipTypename: false,
        withHooks: true,
        withHOC: false,
        withComponent: false,
        useExplicitTyping: true,
        exportFragmentSpreadSubTypes: true,
        apolloClientVersion: 3,
        federation: true,
      },
    },
    "./graphql.schema.json": {
      plugins: ["introspection"],
    },
  },
};
```

Example code and error:
```ts
export type CompanyCreateJoinRequestMutationOptions =
  Apollo.BaseMutationOptions<
    CompanyCreateJoinRequestMutation,
    CompanyCreateJoinRequestMutationVariables
  >;
```

Error: **Generic type 'BaseMutationOptions ' requires 4 type argument(s).**

**Comment by asaadawey** [comment]
same here

**Comment by mindaugasnakrosis** [comment]
I am also using Apollo. Wanted to ask is it possible to generate typings purely from schema? Without destination of where the operations and fragment files are declared? Because I don't have either of those in my local repository. Just a schema from backend apollo-server which possesses all the operations and fragments.

**Comment by dotansimha** [comment]
This is an issue with Apollo-Client v3.4, see: https://github.com/apollographql/apollo-client/issues/8407 , they introduced a breaking change for the generics.

I created this PR as a temporary workaround to make it work in this PR:

You can use `@graphql-codegen/typescript-react-apollo@2.2.7-alpha-5cbc35bf.0`. I can't promise this will be in a stable future version of the plugin since I prefer Apollo to add a default type for their generics.

**Comment by dotansimha** [comment]
This was fixed in Apollo-Client (https://github.com/apollographql/apollo-client/pull/8423), so regular setup of codegen should work the same now, even without https://github.com/dotansimha/graphql-code-generator/pull/6152 . We can close this one :)
