### ISSUE TITLE
Resolver input field type for non-null input with default is optional

### ISSUE THREAD

**Issue by ThomWright** [dotansimha/graphql-code-generator#6119]
**Describe the bug**

I'm writing TypeScript resolvers. When I have a non-null field with a default value on my input type, I expect my resolver input type to also be non-null (and not undefined).

**To Reproduce**

1. My GraphQL schema:

```graphql
schema {
  query: Query
}

type Query {
  myQuery(input: MyInput!): String
}

input MyInput {
  aspectRatio: Float! = 1.25
}
```

2. My GraphQL operations:

N/A

3. My `codegen.yml` config file:

```yml
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-resolvers
```

**Expected behavior**

My input type to be:

```typescript
export type MyInput = {
  aspectRatio: Scalars['Float'];
};
```

Instead, `aspectRatio` is optional:

```typescript
export type MyInput = {
  aspectRatio?: Scalars['Float'];
};
```

**Environment:**

- OS: Ubuntu
- `@graphql-codegen/...`: 
  - `@graphql-codegen/cli@1.21.5`
  - `@graphql-codegen/typescript@1.22.1`
  - `@graphql-codegen/typescript-resolvers@1.19.2`
- NodeJS: 14

**Additional context**

N/A

**Comment by dotansimha** [comment]
Input types are tricky because they act differently for the client of the schema, and for the resolvers.
We decided to generate the basics based on the schema, and then modify it in-place where needed.

You shouldn't use `MyInput` directly when working with the `resolvers` plugin. Just use the root `Resolver` type or `QueryResolvers` and everything will be typed correctly, since we apply `RequireFields<QueryMyQueryArgs, 'input'>` for the resolvers definition.
