### ISSUE TITLE
`skipDocumentsValidation` doesn't work.

### ISSUE THREAD

**Issue by dmitrif** [dotansimha/graphql-code-generator#6354]
**Describe the bug**
In my use-case, I want to run a series of documents through a custom plugin. As it is not generating consumable types, I do not care for the validation. The documents contain multiple queries with the same name. 

Attempting to pass in `skipDocumentsValidation` through config file, gets ignored.

**To Reproduce**
https://codesandbox.io/s/sharp-germain-5yjrs

**Expected behavior**
Duplicate name error is not thrown.

**Additional context**
N/A

**Comment by mogelbrod** [comment]
This still seems to be broken in @graphql-codegen/cli@2.3.0.
Related docs (where the option is documented): https://www.graphql-code-generator.com/docs/config-reference/codegen-config#available-options

**Comment by mogelbrod** [comment]
Just to clarify the impact of this being broken:
The CLI outputs nothing if any kind of validation error occurs, meaning it's not possible to evaluate small changes to a subset of a schema without also making sure that the entire schema is 100% valid. In my case this prevents me from switching between a staging and production API due to minor discrepancies between the two.

**Comment by ardatan** [comment]
https://codesandbox.io/s/trusting-zhukovsky-zkdk6?file=/codegen.yml
I think this works as expected with the latest versions.

**Comment by mogelbrod** [comment]
@ardatan Looks like setting `extensions.codegen.generates[*].config.skipDocumentsValidation = true` in the YAML config did the trick indeed, thanks!
