### ISSUE TITLE
`plugin typescript-urql` Promises support

### ISSUE THREAD

**Issue by jhonatanmacazana** [dotansimha/graphql-code-generator#6421]
**Is your feature request related to a problem? Please describe.**
`urql` has official support for promises when using queries and mutations, as shown [here][1]. Right now, the `typescript-urql` plugin supports _Components_ and _Hooks_, but _Promises_ can be really useful for decoupling code.

**Describe the solution you'd like**
Modifying the plugin to support an option like `withPromises: boolean` which generates code to use _Promises_.

**Describe alternatives you've considered**
I am using _Promises_ for queries and mutations as shown in the [official docs][1] with the `useClient` hook to access the urql's client.

[1]: https://formidable.com/open-source/urql/docs/api/core/#clientquery

**Comment by dotansimha** [comment]
You are right, we don't have generated code for that purpose. 
Since most of the GraphQL clients are adopting the TypedDocumentNode (Urql also supports it), I can recommend on moving to `typed-docucment-node` plugin instead, and this should provide you an end-to-end type-safety for the entire Urql API.
