### ISSUE TITLE
@graphql-codegen/cli is flagged as vulnerable due to dependency on ansi-regex 3.0.0 via listr-update-renderer

### ISSUE THREAD

**Issue by sgb-io** [dotansimha/graphql-code-generator#7014]
ansi-regex 3.0.0 is affected by a high severity vulnerability: https://snyk.io/test/npm/ansi-regex/3.0.0

This is via `listr-update-renderer` which seems to be unmaintained at present.

**Comment by sgb-io** [comment]
Also see https://github.com/SamVerschueren/listr-update-renderer/issues/29

**Comment by tvvignesh** [comment]
@ardatan PR raised for this issue here: https://github.com/dotansimha/graphql-code-generator/pull/7210

**Comment by ardatan** [comment]
GraphQL Codegen is a CLI tool, we don't think a slow execution in an edge case can be considered as vulnerability and this doesn't affect the end user of your project at all. Since it is an indirect dependency of our package, we have nothing much to do about it. You can use yarn resolutions to enforce "non-vulnerable" newer version. 
I'd also recommend you to read this article about how `npm audit` mostly causes false alarms.
https://overreacted.io/npm-audit-broken-by-design/
