### ISSUE TITLE
Some thoughts compared to graphqlgen

### ISSUE THREAD

**Issue by benawad** [dotansimha/graphql-code-generator#740]
So I just tried out https://github.com/prisma/graphqlgen and this library with the following template: graphql-codegen-typescript-template to create Typescript types for resolvers.

I wanted to give some feedback on some things I liked better about graphqlgen.

1. If a query/mutation doesn’t have any arguments, graphqlgen generates the args Typescript type as `{}` which I like better than the template which uses `any`.

2. graphqlgen let’s me set what the `Context` type is upfront, so I don’t have to do `QueryResolvers.Resolvers<Context>`, I can just do `QueryResolvers.Resolvers`.

3. I’m not sure how to handle this case: 

So my schema is this:
```
type Post {
  id: ID!
  title: String!
  content: String!
  published: Boolean!
  author: User!
}

type User {
  id: ID!
  name: String
}

type Query {
  post(id: ID!): Post
}
```

So in the `post` resolver it expects me to return an `author`, but I really want to return a `authorId` and have the `Post.author` resolver use the `authorId` to fetch and return an `author`. graphqlgen solves this by allowing you to create your own typescript types and it will use those.

**Comment by darkbasic** [comment]
Regarding number 3 I suggest you to have a look at the `graphql-codegen-typescript-mongodb-template` template: https://github.com/dotansimha/graphql-code-generator/tree/master/packages/templates/typescript-mongodb

It allows you to define the following schema:
```
type Post @entity {
  id: ID! @id
  title: String! @column
  author: User! @column(overrideType: "string") @map(path: "createdBy")
}
```

It will generate the following types:
```
export interface Poll {
  id?: string | null;
  title?: string | null;
  user?: User | null;
}

export interface PostDbObject {
  _id: ObjectID | null;
  title: string | null;
  createdBy: string | null;
}
```

So you can use `Poll` for the object returned by the resolver and `PostDbObject` for the object returned by the database.

**Comment by benawad** [comment]
@darkbasic thanks, I'll check it out that looks good

@kamilkisiela sweet

**Comment by dotansimha** [comment]
Thank you @benawad !

Regarding #1, @kamilkisiela already did a fix for it: https://github.com/dotansimha/graphql-code-generator/pull/741  . We loved this feedback but actually thought to take it a step further and to use `never` in this case instead of `{}`, because this way it will enforce that `args` is not in use, because it’s empty for sure.

Regarding #2, As @kamilkisiela said, we have support for this use case, any you can override it easily. If you wish to change the default value, we added support for this in this PR: https://github.com/dotansimha/graphql-code-generator/pull/743

Regarding #3, as @kamilkisiela mentioned above, you can override every type because we are using generics in the generated resolvers and we think it’s a nicer solution to that issue.
But! I also want to add that think this approach of returning the `id` from a query resolver might not be that efficient and good practice, because this way you have to fetch the whole object by id in each `Post.` field, instead of fetching it only once.  we would encourage you not to do it and same goes for our users

**Comment by dotansimha** [comment]
@benawad If you are using dataloader to batch requests then it's great :) Then your resolver should expect to get then full object and not just the id, but the linked resolvers should return `string` in order to fetch it from the dataloader. 

Then you should be able to use the generics to override the return value of each resolver, and set it to `string`. And with the latest version you can override the `Parent` value (using generics).

Also, @kamilkisiela added a `mappers` features in [this PR](https://github.com/dotansimha/graphql-code-generator/pull/757), so now you can also custom mapping between GraphQL types and TypeScript interfaces, and this way it will override it in the whole generated file (and then you don't have to use generics each time).
