### ISSUE TITLE
High severity GitHub security warning due to @graphql-codegen dependency

### ISSUE THREAD

**Issue by tsongas** [dotansimha/graphql-code-generator#7823]
I'm getting a Dependabot alert saying "node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor" then:

```
Dependabot cannot update node-fetch to a non-vulnerable version
The latest possible version that can be installed is 2.6.1 because of the following conflicting dependencies:

@graphql-codegen/cli@2.6.2 requires node-fetch@2.6.1 via a transitive dependency on cross-fetch@3.1.4
@graphql-codegen/typescript@2.4.7 requires node-fetch@2.6.1 via a transitive dependency on cross-fetch@3.1.4
@graphql-codegen/typescript-resolvers@2.6.0 requires node-fetch@2.6.1 via a transitive dependency on cross-fetch@3.1.4

The earliest fixed version is 2.6.7.
```

Is there a dependency update in the works to fix this?

**Comment by ardatan** [comment]
Not sure if plugins have dependency because you didn't share the dependency graph but CLI has a ranged dependency for loader packages `@graphql-tools/url-loader` etc that uses `node-fetch` under the hood. And their latest versions don't have a dependency of `cross-fetch` and older `node-fetch`.
I'd recommend you to delete and create your lock file from scratch in order to get recent versions. Not sure if it is worth on our side to update the ranges. Let me know what you think @dotansimha. However I'll create a PR to update our lockfile.
Also I'm not sure what are details of this security thing but GraphQL Codegen is a CLI tool that runs on your local not in production app. About npm audit things, please see; https://overreacted.io/npm-audit-broken-by-design/
