### ISSUE TITLE
dependency issue please update dependenices for 

### ISSUE THREAD

**Issue by reduxdj** [dotansimha/graphql-code-generator#7825]
"@graphql-codegen/typescript": "^2.4.8",

"@graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > @graphql-tools/relay-operation-optimizer > relay-compiler@12.0.0" has incorrect peer dependency "graphql@^15.0.0".

### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on [GitHub](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)

> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the Codegen and plugins version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

**To Reproduce**

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yaml
# Put your YML here
```

**Expected behavior**

**Environment:**

- OS:
- `@graphql-codegen/...`:
- NodeJS:

**Additional context**

**Comment by jekh** [comment]
Is this issue about the transitive dependency on `relay-compiler`, which requires a peer of `graphql@^15` and does not allow `graphql@^16`? I see this warning all the time with pnpm. The output is:
```
 WARN  Issues with peer dependencies found
.
└─┬ @graphql-codegen/typed-document-node
  └─┬ @graphql-codegen/visitor-plugin-common
    └─┬ @graphql-tools/relay-operation-optimizer
      └─┬ relay-compiler
        └── ✕ unmet peer graphql@^15.0.0: found 16.5.0
```

Would it make sense for `@graphql-codegen/visitor-plugin-common` to declare an optional peer dependency on `@graphql-tools/relay-operation-optimizer`, rather than a regular dependency? The `@graphql-tools/relay-operation-optimizer` package appears to be used when the `flattenGeneratedTypes` config option is true (I don't use that config option or relay, so I'm not familiar with the use case).

Perhaps somebody with a bit more expertise on how the [`optimizeOperations` function ](https://github.com/dotansimha/graphql-code-generator/blob/6470e6cc986274d450c405abeb9aa55c3fa6b6ab/packages/plugins/other/visitor-plugin-common/src/optimize-operations.ts) is used/intended to be used could weigh in on whether it makes sense for `relay-operation-optimizer` to be optional?

**Comment by TLadd** [comment]
I ran into [an issue](https://github.com/facebook/relay/issues/3919) where I was actually using react-relay and relay-compiler in another package within a monorepo that also makes use of graphql-codegen. Having two versions of the relay-compiler in the repo resulted in some resolution issues. Declaring `@graphql-tools/relay-operation-optimizer` as an optional peer would be nice.

**Comment by Urigo** [comment]
@ardatan you solved it with the latest version right?

**Comment by ardatan** [comment]
Yes it should have been fixed already.

**Comment by Urigo** [comment]
closing, please reopen if the latest version doesn't fix it for you
