### ISSUE TITLE
[client-preset] optional `' $fragmentName'` property

### ISSUE THREAD

**Issue by n1ru4l** [dotansimha/graphql-code-generator#8440]
```ts
export type UserFieldsFragment = { __typename?: 'User', id: string, email: string, fullName: string, displayName: string, provider: AuthProvider, isAdmin: boolean }
  & { ' $fragmentName': 'UserFieldsFragment' };
```

The following:

```ts
{ ' $fragmentName': 'UserFieldsFragment' }
```

Should be:

```ts
{ ' $fragmentName'?: 'UserFieldsFragment' }
```

**Comment by ZakKa89** [comment]
Same issue here:

`export type HeaderImageFragment = { __typename?: 'Image', url: string, alt?: string | null, id: string } & { ' $fragmentName': 'HeaderImageFragment' };`

**Comment by ZakKa89** [comment]
I solved this by using this:

https://www.the-guild.dev/graphql/codegen/plugins/presets/gql-tag-operations-preset

This is now the recommended approach by the team, see also this article:
https://the-guild.dev/blog/unleash-the-power-of-fragments-with-graphql-codegen

It was a bit annoying because in other parts of the documentation, like the installation guide it doesn't state this yet.

**Comment by ZakKa89** [comment]
What I would like to know is why use the  DocumentType helper instead of just: 

import { HeaderImageFragment } from '@/types/gql/graphql'

**Comment by n1ru4l** [comment]
> What I would like to know is why use the DocumentType helper instead of just:
>
> import { HeaderImageFragment } from '@/types/gql/graphql'

Not sure what you are referring to 😅

Can you provide a full example?

**Comment by n1ru4l** [comment]
@ZakKa89 Not also that the [`client-preset`](https://www.the-guild.dev/graphql/codegen/docs/guides/react-vue) replaces [`gql-tag-operations-preset`](https://www.the-guild.dev/graphql/codegen/plugins/presets/gql-tag-operations-preset).

**Comment by ZakKa89** [comment]
First off, thank you for responding @n1ru4l ! 



> > What I would like to know is why use the DocumentType helper instead of just:
> > import { HeaderImageFragment } from '@/types/gql/graphql'
> 
> Not sure what you are referring to 😅
> 
> Can you provide a full example?
> 
> Maybe this blog post also helps you understand why? https://www.the-guild.dev/blog/unleash-the-power-of-fragments-with-graphql-codegen

I read that blog post thanks, but it doesn't help me understanding the following:

In this guide https://www.the-guild.dev/graphql/codegen/plugins/presets/gql-tag-operations-preset 

the following code is found:   `tweet: DocumentType<typeof TweetFragment>

And I don't understand we can't just use `  tweet: TweetFragment`

since that type is also available in the generated types, and has the types I need? Does that example help with understanding the question? 



> @ZakKa89 Not also that the [`client-preset`](https://www.the-guild.dev/graphql/codegen/docs/guides/react-vue) replaces [`gql-tag-operations-preset`](https://www.the-guild.dev/graphql/codegen/plugins/presets/gql-tag-operations-preset).


So are you I should use client-present over gql-tag-operations? I thought I read somewhere in the docs that gql-tag-operations was the preferred way right now, but can't find it.

**Comment by charlypoly** [comment]
Hi @ZakKa89,

> the following code is found: `tweet: DocumentType
> 
> And I don't understand we can't just use ` tweet: TweetFragment`
> 
> since that type is also available in the generated types, and has the types I need? Does that example help with understanding the question?

The fragment type is wrapped in a `TypedDocumentNode<R,V>` type, making it impossible to directly extract the inner type (the actual fragment type):

<img width="848" alt="image" src="https://user-images.githubusercontent.com/1252066/195549560-89a7375e-6f38-49c2-a009-5c1c0ce84f6c.png">



> So are you I should use client-present over gql-tag-operations? I thought I read somewhere in the docs that gql-tag-operations was the preferred way right now, but can't find it.

You are right, we only updated the guides for now: https://www.the-guild.dev/graphql/codegen/docs/guides/react-vue
We plan to update the doc of `gql-tag-operations` and deprecate is on `npm` in the upcoming weeks.

**Comment by ZakKa89** [comment]
Thank you I will try that. That might also solve this issue https://github.com/dotansimha/graphql-code-generator/issues/8474
