### ISSUE TITLE
The webpack plugin is not compatible with the latest version of graphql-code-generator

### ISSUE THREAD

**Issue by polco** [dotansimha/graphql-code-generator#897]
**Is your feature request related to a problem? Please describe.**
after updating to the latest version of `graphql-code-generator@14.0.1`, i get this error when compiling with webpack:
```
Unknown codegen template: "graphql-codegen-typescript-template"
```

**Describe the solution you'd like**
the webpack plugin API needs to be updated since the 'template' parameters does not exist anymore.

**Comment by dotansimha** [comment]
Hi @polco !
We removed the webpack plugin for now. We tried to implement it and released an initial version of it, but it doesn't really work as we expected. 
It's not possible to force Webpack to reload the files when a TypeScript interface changes. So it you change a GraphQL file -> The codegen runs, writes to output file -> The output file updates, but Webpack doesn't get the file update and it does not compile (because an `interface` change does not trigger TypeScript compilation).

@kamilkisiela do you think we should keep trying to find a solution for this?

**Comment by dotansimha** [comment]
Closing for now. We might try to implement again later in the future.

**Comment by dotansimha** [comment]
Yeah it's in git history, you can take a look at 0.13 tag.
