### ISSUE TITLE
How to generate ts-multiple?

### ISSUE THREAD

**Issue by azazdeaz** [dotansimha/graphql-code-generator#908]
The examples contain a `ts-multiple` folder with separated files per query/type/etc. I read through the new docs (which is awesome! thanks a lot :metal: ) and played with the settings but i couldn't figure it out how to generate multiple files. What did i miss?

**Comment by dotansimha** [comment]
Hi @azazdeaz ! 
The `ts-multiple` was a template we had a long time ago, and it was deprecated and then removed.
It was very difficult to maintain the multiple-files template because of the imports and circular dependencies between them.

https://github.com/dotansimha/graphql-code-generator/issues/732
