### ISSUE TITLE
Support type-only imports when using verbatimModuleSyntax

### ISSUE THREAD

**Issue by cs-clarence** [dotansimha/graphql-code-generator#9595]
### Is your feature request related to a problem? Please describe.

[TypeScript 5.0 Release](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html) introduced `verbatimModuleSyntax` option which simplifies import elision rules when handling type only imports. With the new option, the user must explicitly specify which imports are type only.

Assuming `Type` is only used as a type, this:
```ts
import { Type } from "./module";
```

should be updated into this:
```ts
import type { Type } from "./module";
```

Currently, however, the codegen has no support for this yet causing issues for projects using `verbatimModuleSyntax`.

### Describe the solution you'd like

There should be an option to the codegen: something like `explicitTypeOnlyImports` or read the tsconfig file if `verbatimModuleSyntax` is set to true.

**Comment by Bauxitedev** [comment]
Why did you close this issue? I have the exact same issue in my Vue 3 project.

When creating a new project using Vue 3 and `npm create vue@latest`, your `tsconfig.json` by default inherits from `@vue/tsconfig/tsconfig.json`, which states:
```
    // <https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#verbatimmodulesyntax>
    // Any imports or exports without a type modifier are left around. This is important for `<script setup>`.
    // Anything that uses the type modifier is dropped entirely.
    "verbatimModuleSyntax": true,
```

So setting "verbatimModuleSyntax" to false is not a good solution, since it will break imports in `<script setup>` in Vue 3 projects.

You can go into the imported code and replace all `import { Foo }` by `import type { Foo }` manually, but this is also not a good solution, since you'll have to do this every single time you run the code generation step.



Any ideas?
