### ISSUE TITLE
Provide the optimization plugin for Next.js

### ISSUE THREAD

**Issue by kaorun343** [dotansimha/graphql-code-generator#9762]
### Is your feature request related to a problem? Please describe.

The Current SWC plugin doesn't work well with recent Next.js. 
In order to reduce bundle size in Next.js application, we have to use its babel plugin so we have to put custom babel config file, which disables SWC compiler.

### Describe the solution you'd like

My suggestion is providing the optimization plugin for Next.js, which wraps `babelOptimizerPlugin`.
We don't have to care about SWC version mismatch. 
Also, we don't have to prepare custom babel config file, so we can still get benefits from Next.js's SWC compiler.
(I'm not familier with Next.js plugin system, so this explanation might be wrong.)

### Is your feature request related to a problem? Please describe.

- https://github.com/dotansimha/graphql-code-generator/issues/9450

**Comment by YassinEldeeb** [comment]
Hey @kaorun343! The SWC issue is indeed quite a complex topic, read https://github.com/swc-project/swc/issues/8315 for more context.

> My suggestion is providing the optimization plugin for Next.js, which wraps `babelOptimizerPlugin`.
> We don't have to care about SWC version mismatch.

Unfortuntely, that's not possible, `babelOptimizerPlugin` comes from our `client-preset` package which we maintain in Javascript, Next.js compiler plugins are only written in Rust, because SWC, the underlying compiler is written in Rust, that's why we need to have a completely separate package with separate challenges for the SWC plugin.

We can't simply port it, or wrap it for Next.js usage.

**Comment by kaorun343** [comment]
Hi, @YassinEldeeb!
 
Thanks for your reply! 👍 

I checked the other packages that provides plugins for Next.js, and I found they uses babel internally. So, it might be possible to do so, I think.

- vanilla-extract provides `@vanilla-extract/next-plugin` , which is based on `@vanilla-extract/integration` and this uses babel internally
  - https://github.com/vanilla-extract-css/vanilla-extract/tree/master/packages/next-plugin
- Kuma UI also provides `@kuma-ui/next-plugin` , which uses `@kuma-ui/webpack-plugin` and this uses babel internally, too.
  - https://github.com/kuma-ui/kuma-ui/tree/main/packages/next-plugin

They seems setting their original webpack loader in `webpackFinal` function.
